---
apiVersion: v1
kind: Secret
metadata:
  name: hive-iceberg-postgresql-credentials
  namespace: platform
type: Opaque
stringData:
  database: hive-iceberg
  password: hive-iceberg
  postgres-password: w70lpAuF73
  username: hive-iceberg
