---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: platform
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgresql-keycloak.shared.svc.cluster.local
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-credentials
      key: username
    passwordSecret:
      name: keycloak-db-credentials
      key: password
  http:
    httpEnabled: true
  hostname:
    strict: false
    backchannelDynamic: false
  proxy:
    headers: xforwarded
  bootstrapAdmin:
    user:
      secret: keycloak-bootstrap-admin
