---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: keycloak-demo-passwords
  namespace: platform
spec:
  encryptedData:
    demo_admin_password: AgBwQWk2bgJhhhjhWrnqUMwBTucwUAqc+f9aeM4IL/iTQTUOjc1PouLgscGTI+vTPMvCtQxMW5jcRblcNLV6WL2lAwJfAiqq7AYaWEQ3V0nUsag8en49J3eDqtb82S8BV8Zg7+nxhg9Wya6/zBWmmzdKq+LJZYzrgv7tjps5yV1qIjI3Z2WCFTeBOQ6V/Y41HeKayil0C4jO3v+P2pHTyboRyvHPYfzifuoNVWQ5zhK0px5oRObFSi2+MBAy1GCWCylkdOavwI8gCbKAeKiwHGQ6GPsw72INjxSF2E4Ncna1jpYXJlnzDuSlVWhCXVUwrAbQhc5zzH2VNomcG54gK+Z0dcnjcF3aqxWhJo55HrI7fK4KTFhkWxI5xm9KNWXyD1XggNM2bqFZZNELyivukcoJB0kdD69cHUxxPf1/Y+mijb0JKaiwN2I1Ru53JqseY36F5Ep/XgU+w6/Z1srkML3M+BXc7Nx1o1HbDsuSuqC4XkEsd8DzFsfbsl+/iKUeNPiBNT0tip+mpYXcCdbzimaWqERRviuYlAHZTJS7VPi0fPjSabNYinl7SrxFS4JTjU5ungxaOZ2dG+gUUyUFhBD9YtapuSN8cG13uuu2xYO3I/e4g8K97EQsACLE1lYi5ZSNpCtcc4cb6jdAdy+EOBLP6uGPKEbrRjdu7R0M17+f/M8tkpcK/vap9EqCF9j9wF9jHsAFiia9Vtvti3frRnAz373WGDN4guuz4xMnME8tZA==
    demo_user_password: AgAFVwY+FOhFjsBdpeOdIuypFzP4p0xA/akXITi6EyMPnum/GktNZd7VRdVm34Fn7qmg4Bmz94dAH/ZzKwqCwokDhi7SUs1Eiyku31Vygn9wvCIkQBVgeXkdtgtI+RwolMw0QReLPzaJg1FzrI/o8DXMCVmEJ+kaP1Qz2IZ4ybnIdcyORwBp+//heJoZ+PwGzVXZrB14vnnBywA26C+x3BpxhU9kpYWbS9r/mlWn4OUezRZ9i6ANmCAHywpFmJI2m1NWJLoh3woIyfkTOh1+CkYsVGkS34mg7e1P+g9vew750T8zkS9CIHb408If1pezGi7isoOGbK3xwrWpCkulpsFh4KOob9Qz5fVJRcZDX/AIV8I7jHlWGF895cG7SzOHLOiHOFiTw2YrjLsbLKrqFl1wm8XnstqrY4kp9nFXUc1IIQDjdmEooO41CD1Wzvgz+A3834izzgJf3Rear3bxoIVebBefKuQLMygylcx8+UB7o35ASH8gP84zTXnK3Uz9iplvK/70idvTckgtO5AviDsq+cYuAKkCEXgt8XcVRkcPt8OuMsXQiAb3FU++VWNt5LrcOEhXiIsiY2WSwQrzEzqgDjeclsmpltoCGZsH0/ZyIGzplNBKVqW7dDsyitMo+j/8xauUUVmgGatKSuHFntSSXfWfbk37XSwnrYO8JLZmiyi47aBUzqE9FBWjoiFJDI8lKusGgi9CSHzkSDSSIcZYAfsoVLVqo/Chtpeu9NSSaQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: keycloak-demo-passwords
      namespace: platform
    type: Opaque
