---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: keycloak-demo-passwords
  namespace: platform
spec:
  encryptedData:
    demo_admin_password: AgAYBKyXvUwBi9FB2QJKg/MSdLAqbKBlXVKEyPu5DA6yeNP1Js7JU76tYiZTwWYcaP/4g1OxqBVcahCRoMX3HcgUfnzawmUO5A32kTnEfqdBL9snVxzHpQzYlVhwSAK/NusxRtO5CkxRbcCP/kN67ymBV57htkYtp2vz5y2rEmwr8/vtfIQ7j+jHhqtRs5yrcdXebxU5WtsZ22mfvpNrZzXmdpMWgGRqEJ9d3jmCofW+GFhPBX+04Ei7QXP5D3GrBqoyvAJr5ko+heLyzKf7y+tQNmO7tkw8iJR4lxuY3iC2AX4OKJa24qi/StUt9douQrRNqH5VNw+m1SIFDUUsZtmcQSSgcl2WtupcUxbZeljSmZFMDMDolUrywSJBf3DojyDny2YSTfmfTGH3DqRkhyx1P5ae0FX9naB+SFEesdbLZGNB/zyDFc3FbLwFsdDOro9pap46kliF77vjr+ugo0fAYIXtN03YROyBg8fGyo5SvkSit7frKI8oaNAEwELxcteU0zDXdj7QWX5MfMNzctUhKl91BvpZdRQAEszub037vbq0Ztnue6IxGF+cu5VJgE2kJZm1P8O6qALO/E4BwwLaW8gG0vpvyG/AfB/u9rpwSFgyZAHrqvNHE57xFn+AteUE8rg/9mPwpFQK//BZWpsaJ5oG1d4X0qQfMIZ4W1II0joOXE1tK73hHbCY0Ai6pxBMnt08fNiPBFxZ0bDK27GSz2mfxQMXivGmZBpPDftSLQ==
    demo_user_password: AgCywT1xOY9sADAWuUnlBUcBDk+F8YZhd4+lXETijdxZlHsWgGmKObqrEu/yntVQRFh0DmC2Ah+DUfbqLLUH9bCZMSIU/Ggm/hM9U8t3ajwaj8CRBspQd/5Vw6iyiqN4Ov0XFVjwdvK61II2KXBjl4uudxrQiR7GT3P/Hn3vDh7heTRuhiihcYOmL3X4onc8jKxj/o+3q8mtRU+st/16iV7ih5G+65ZL58MDsQKIqU3QVhDo6tm/wj8iwPw+13PirLDb/9dcq5mYAt4ro2ZwnN2I0xRz5sgwlWYhwosyH3OInmNeA8CfWB4bu+EatT/mV5K4EM37ZBPGX0GHUo11zL+S1ewBzwa9InkNQLaGrorlVqZhLkEqfm+G7XmJOefxK0Wdkn/PyJxAZvODgqcJTV7n5WNCRzbZJR+ZSQ4z7d9GFUW4clgBit7fZN3TzhlpVUS/Wzs93xyV9BYMHSeF3xwnoFggY6E09wybGEl/j690US5mNZDJQ0k9aFZLBPEjs2q0UdbyhSkjuohe5WLXgldTirKA9TF1GZfJ6ZBJgzibBWomZQOg8750MQHYjbvxn9d2iitD+HVos8/HxvoUEC5Gq02hKyI+TlUhzoK1No37V9EecaNpSUeKkU6wcYtmhgdVvSIg1/D5g3qMPcdsC+ZaPxR76nC/x9aMwWGxMhhIauHjqUGkahN6clWYZQeOD86sDpuEHBsuieohIY3wfRv4AfOKJncGj9H867Rz0yLBuw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: keycloak-demo-passwords
      namespace: platform
    type: Opaque
