---
apiVersion: v1
kind: Secret
metadata:
  name: superset-postgresql-credentials
type: Opaque
stringData:
  database: superset
  password: superset
  postgres-password: w70lpAuF73
  username: superset
