tpch_demo:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      host: trino-coordinator
      port: 8443
      user: admin
      schema: demo
      catalog: hive-iceberg
      http_scheme: https
      ssl_verify: false
      session_properties:
        query_max_run_time: 5m