---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-grafana-credentials
  namespace: platform
spec:
  encryptedData:
    password: AgCZwzAIQd7s97ERz3cj2LwjZFJKEZmjedFWQ3t01ZJm0TbexUXJryntl+JgFE2XMOJZb66YopDL2+Ai+pE1q1mguOctb8Bc9nJnpoE8VRPKbl2Sk/M1yFguFqmdlUZd667xx+UVNXxGoG/8FLK3tTOPRHNSLBDnFjz6m+HcT9EEF7QDgur33rjovoc4BoivTDqdpnr38Q3EFwaigfWowlcGO6jrHtYN8vE5iAreFgCG+D/OgTFfMIGsmjp3DSqewnvO9eW0lX1Py3AbGfW7/BmC4GC1lcUUlYhZ+6M07/U8kQGsxYSkBuRJ42tQDY7QMGpgvEQliBbTGFeqHkfbemtrCS58hltIdMJkB0qlV+zptrFnAHRShAu2SryAKd2b3jS6JkATB4VuLiJVnNkgQGhVMTs2QigXdbzgqVZCRU0Rc5iJJdiOZPJpph7Kzk2jGjuvyokMPqGgCAMkOdVVpJGlLF5+t2RHuG2Ulpuc94Y0nwUd9S4iP6bfu3qBnMdnAfCNcSFDVgolL7F+K++4A7dV79cFT/6ruAOgLew+XidiEEAVuMlI7BoZ7xqn6Dj4/aY73Zvvrw1MAPLbEcMnh1rMQ0mEienCMeO92fz1WOD9mXuef83tokcnAdnMQCAhenSQJeHIvsJ6ZApCzIyiz1h3T29vGyxhpzjbHqz57jjgKXJknqzsKvxZ8Lp6Mi0ghAiTQFGDA36G9I+LLyn0WhjXNpx6N+narRU=
    username: AgCLsAtmOtLp4zRnDkfjl68VkERvDOLkO8KS02bsxIaKRaIyGYOEqIUp3AYf/dJakdiXZktekJdSbXTh2UCiVh+LsIiY/C4vSPI32dshRCni1RDRzUdzoH+NJejt6+FCtG4jdWO1CH71a08LJO5AE0Hlb6ugh+O3zTycewokSuLwE9/wibIgjDgGSS9dAdTcSPGECz9cx+SMurw6IlE4J35Fe6JKW7mxo5hAftp++2KO0tQGSu7+B3/Pnuzbz7hUENUMEmhWnLfpWuOxGped8N8czWtXETeA8Lag+7ckF++ZCyq2fOUnadPzlCRxJSH05rNdCthGgvBVavvJ+q37n8Lo7b26PD1OsQ/vP6D51Lq9sboXx9inCw00cBHyS0YUVyrOd3xDOch2O7KkTMwbXTps68wy303qjk+nTzimi45pvXRS75dIXCyjqrTR+p5q/V+6OvPxQ6ERetuYVT4thLP5l6ZAhpbB8JP0+8VyjcWPQFl4QlV2CpWxdJFGQsYTMFWT1ZG2MexUYfYwGeRKnIolYj1IFJtfMAKDb3PeOhCnHDTkgFLk+ce4AQXORIuBY24OVidA/rXEwK85j0lF3tGyDvBe1ihJ12KbNpQ+JapgMvMH3+qeCYVOZG4c9WV4riJ2HAA2gapJhSKR7KHvjzstLSVbVIIqjOrgM9Ay+uFmBZ33mhKKQlS8nB3aI557LJLlP7j3cswC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-grafana-credentials
      namespace: platform
    type: Opaque
