---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-prometheus-credentials
  namespace: platform
spec:
  encryptedData:
    password: AgA9s0tV27eDwaWMMEV9lNGtKV6JTF9q1odCa+oWEuoeczc8MqF5tUEr/vcU2km5RoR8hdIV4d93Pc4V6uXnAb3x9BoBj7qTO/Cxl3h0PQVjjONBmqnb41ymELmpIigdlVetbhngoO+YkvOj5sSCcglwE1Doi4MFk2ZymEk++Rivrn0l+uGaKlG+I8VGW7/z35d1b5qg1CyOeVp5qxVsdxEt3J7bwJyK8IUSo4kES84qAKQy/o6gRLDcCRf8Zb7gZU6Z4vZp4CrtReZZgMALFjG7zZMRNhpczIhgp6XNTrVOGWDdW99vj3TFQgYxwb70z30iC7YgrCDZjANcHTAlDDFEKw2E9sivHtRvlfzHWLP0FUXKKk6DpxysggvzxzWjTUolDRyZ7P48axbgc9xxAejTNIIpQehLB4vV1wiaUZiHm3CAxcnn9DL7LpawpTuwmcKOmMx0oK2n6P7g5inRoOS3NsuDmIn3PhWvUNDqWyWdan3V7Q/p8Lhu4896mYIw/im1FDxVPndP2olvEP+vQNsa3jquV3NN0Yhz0BP7hT0RYgm1kFGas3iC1AiTf3F6+yo4b6pitJCV/vcYYIodeXKqhQROV9YQgnjU751Ja+41v1x4NhUl/GsMaOZisIyrnD7wLhc6PFwDPUF1o+JJs1Gq3qeJYnuV+inSEDAkomcW9MBz1iUzIR6Bt6LMCq2Qea4BBz5ySCFZ/fs68+f/Kl/T31KVNgxRVC4=
    username: AgAO4WO7A1rYP+cFQiobX+GwI3WbRaNGGDYPJ4UFR9H4slfj8r2B8NZgMMv3ezdSquffZVN8W2V95uAgxLeRAlG9PMLc7qoLVCAytOGHYegaeVes2GM7vA05I9W5pwiaLlNJW5Sx/AxjPBn1QVkF7F5yfdh4LCbl74oAGIrgsKjXjchZ7XNYYkDvk+fxMnGJIkgBRQ4BggpKZSgch/6GPu/6Yt9qd/JcoHDHzBCnx3NsuRBph4ceWxXMG3EGXZu7oTGZTaQhFv4aWKmZLl7Honf1B1blKgJaSNv7h+HlKVyryt/BJAa0vufAxl6Ukhq4IybcK2WU8Jr1SQm1v+98+0w3ZNpKH2c2B4jqQdOrf/Ko0LOUy1BNtt7dyY3PCiMG677c5ndsjFIkZt5ia39ho96yM1Qxs1SIT+pmCkDPN4Qy/kNR+DEeuhBFqVp+hN0HvxuZFDI1tB/6pST5sDKkSzjkvx9uwqMf9YPJ29B9VYXRm28paz8HtDzFneUGw0XxgStieeY1C3p4r2kbrzSdB6+JLEF7Aip5CsrINVlFEUfjKQjhykJtgJYpD8Q6O8ShC0Wjqq+nrKmYsUCNCSQz1ANiCvk7UWU5RH6d98TmIZTI7HcUDeNUnPTYJRAaRn5ZycJHDdYWmJ5/dSpRo0tzrmtq/1AxmND6P2I9x9NkWZQt8wGCNj4mIptV+MeYDvjEMsXjZA0vl3h4BJce
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-prometheus-credentials
      namespace: platform
    type: Opaque
