---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: kafka
  namespace: platform
spec:
  clusterOperation:
    stopped: false
  clusterConfig:
    metadataManager: kraft
    vectorAggregatorConfigMapName: vector-aggregator-discovery
  image:
    productVersion: "3.9.1"
  brokers:
    config:
      logging:
        enableVectorAgent: true
    roleGroups:
      default:
        replicas: 3
  controllers:
    config:
      logging:
        enableVectorAgent: true
    roleGroups:
      default:
        replicas: 3
