apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: kafka
  namespace: platform
spec:
  clusterOperation:
    stopped: false
  clusterConfig:
    metadataManager: kraft
    vectorAggregatorConfigMapName: vector-aggregator-discovery
  image:
    productVersion: "3.9.1"
  brokers:
    config:
      logging:
        enableVectorAgent: true
      resources:
        cpu:
          min: 100m
    roleGroups:
      default:
        replicas: 1
    podOverrides:
      spec:
        containers:
          - name: vector
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
          - name: kcat-prober
            resources:
              requests:
                cpu: 10m
  controllers:
    config:
      logging:
        enableVectorAgent: true
      resources:
        cpu:
          min: 100m
    roleGroups:
      default:
        replicas: 3
    podOverrides:
      spec:
        containers:
          - name: vector
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
