---
apiVersion: batch/v1
kind: Job
metadata:
  name: trino-sql-job
spec:
  backoffLimit: 50
  template:
    spec:
      containers:
        - name: trino-sql
          image: oci.stackable.tech/sdp/trino:477-stackable0.0.0-dev
          command: ["bash", "/scripts/run.sh"]
          env:
            - name: TRINO_HOST
              value: "trino-coordinator"
            - name: TRINO_PORT
              value: "8443"
          volumeMounts:
            - name: sql
              mountPath: /sql
            - name: script
              mountPath: /scripts
      volumes:
        - name: sql
          configMap:
            name: trino-sql-files
        - name: script
          configMap:
            name: trino-sql-script
            defaultMode: 0755
      restartPolicy: OnFailure
