---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml

configMapGenerator:
  - name: trino-sql-script
    files:
      - run.py

generatorOptions:
  disableNameSuffixHash: true