---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cockpit-secrets
  namespace: platform
spec:
  encryptedData:
    oidc-client-secret: AgBcwk8cJPc7BbEyDWCyI91wov+YxYPogd5KWe2reGG1AlLWcc6L93Ai88yO51FLTlXURBzXeXOhQ5tCTXnoCxirrTRbvuuEf0/9BoVA75XwGNigkVmHlUao4DSb46d9QhPU+iHL2r1eLfE8yWtCjVv8Jg51ocueDuOnM6pGGNj/3wMRvf2r4JQcYJU4q074KwfOf/v3HIxi2i4qnPmnW3dWHZL8NHoXmuxLVJaCkKKJ60p0uSddW2FKvaFijUBFXdcDfqEPqblbzqpVPeZJ0g1GcBz523h0F48rOm154OYfyg4gccLl0VCxPo+xjbkm8R8PXhGsaCu1X5As70ElxmnvhQ1FyXZb+Hn6/MZ4bVneiZdxMrNqvoFI/urUkaeeURrfPiqt+SxER0xH+AXX48tuNjSAjw/ybZOCPGdOAqdYqZeHP7z2zEf/83QuAOEEdVsQSE9wTDUIiztdHisnVdjT3YWmnr3+ykm01jhp560t2+9zdEmL1BGFvFilVv3JHTq5mkbV4V51KgqHup8zvKoD5NVO/1fdh89yIa3PhuosZHewglXOvFxv2a3CBgh6sqAmB64EA4obe856JblZsM3+u7XgeP9mhDDpKZKMZyiywpkI6b+mgELqtge/Ckg65Y9H+cmexLAweC+u8GVEEVHPREQ5IMCLi3q3CZf++SLBOpZPHJKWUkotym3IwSUVUrxqvAofZTZbdAL7tFQARQ==
    session-secret: AgBYnCUyNal5YGf9L31MZcw2fp0kyrIY6ImiuqJvXz02aTiS2X9sjGIr7/F2LOlDty73yWnZL72tx9wUUNkOJCXVSFiVnyer799JN3J3ZKztq16mTV9e1VFRVbAFWBnVQ9QUFYBrFsEpu+vphCzxoCSqTxqxE01bHTfsRVi3l/NiiFzoEPMGzD6qOkSbHX75q85LPQydKsGz7VCYjixd018f1cmcdj+hJ5FlLMdYpg1r7F8d0nL0B3+Xw45gvYLbYz6NWxiEJkygeVk2jSREEfj9HcbpKM1uv9urXCVHkdm5yvq1ObFY0mf3PttJ6UtmOXtEwrrhQvasvOIXTCFr0EX1zZlFv4H98jrtbVt+OuP9TeVWxGuTBc6IDDEJUlSquw8NwQ3Dk4SnyEIKnC24973pYAjXbORZG0a1ZZXFNj+gpYagFfEYDroi1/6O4pLJtY6AJRxPH0/dEAa3pVeoNsfxphNEp3iyhSXJRZu2wLxFwmB0iKVXArlAO6+GStqHlg5KUDuPnM59ytGW7mP8bIIJ4JSP8q0MD5UzLAODw+qDnHJ3b6s5Qq4x+eva0ldh35x1PbHQ3J20fxOvevxRgk7YkJ2aBg2t//J+wiBbACHrsAL4NzklwAfqp4pkIM9tC3FNFp7tRS8ICAbDnNdixY7fC3j4qwvgY95obEk4cXZIV7kuc09Y/DtWjaqOsTje3yA6Xk8VWicHLkEiM8vJBtHivJgZxxGiSwrtiLMrMD+o24X3OI880W1Jr0RrWeibaPqP
    trino-auth-password: AgAApjvvEClkmvx1fa/eLr5mSRUzs1T/GXz8P0NcTEQqsErHT6Psx6OHVfgQ2DnI4s+HtB0hO3LoYOmSlA1xf0tJXdnHkJwb4sqCj71IZHSLAJwrox6tqmygAkKyeMrPV28zlDAgdrZ+U7EhBH7vo6OdnSudkMVeUtuB6WxxpzvEgpDAH40ewo6UDVzHDJFdtjv141Ei89g/KdkE5VCzvlX87LhX5zEsLR3lTVCg09hN7eCm7VATFbgTWSOdq/U3YaFJjW0qi8En4vJSNF4aWg4ovwJ2yUngBLYiydSdW4UCogv67oi99OrYtC0gTt9tfioJwIapRqohTfAdj+RcbPUJy/g6PZ+AyyXFw10h3mfpNDljjlzmbRw5KBp8HH05mj79VP2fC7kYeWECPhCa1wbtjSWMkII29J8rYbA1zugzT8ey2khacfb2/k9fpU5vAYeUE0SRio2Hot8bt9VMQPSFoW5v8Uzi6pnjzrJUEuVcWjSUZcXdeAbdOTjw3jwYWOK/VdbaLWzbA7711Dc191qovNQsv5A1Q6Zv3lI2PvdbzZBkW/IzY5k/nXJi51otu1nCnWOp1uyLPaOZ3LLrX6Q6H3J0MaFvcXuA9ogsBpn522Ppmh5zD2ecWAJY6Gi7YfRnku2AE3A3oX0LfrS20xp5VsJf1BAvUfgqZmHxD6Gsu/wGaTjXmS97pt/XFiGTfrkB3wMaLskcWr0xsAzxPA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cockpit-secrets
      namespace: platform
    type: Opaque
