---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  # The name of the catalog as it will appear in Trino
  name: tpcds
  # TrinoCluster can use these labels to select which catalogs to include
  labels:
    trino: trino
spec:
  connector:
    tpcds: {} # No options needed
