---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-trino-credentials
  namespace: platform
spec:
  encryptedData:
    password: AgAM8gSTsTfDQi2ribosNVXjRdofiJLcyT0JgR77n/cy7+6ziZ6QGBSUf24bdGLVSWmHOq6oLsfATe7zj0iNbn64eTV9pk4QVTXj7xeaAx5mMZYV6Dzo/uTbsf5lTWF08Sakj01OP7y87Phf+XVOmi+CUgyxaeIY4xmcSqRZB4en9uvGhgu0sDtdYUZ9yt51L6DcLOyekS7MP5ipXvyU/S58XAql1nKGr1sbOCZivC1RQ6pSSoVPP7hR/OCyg7Sp1imKq4e/iWvBesHn/0rXL+qxbXLnUg0r4X+1Bt2WdDLamKAxLepG5jO8+O+uvDoXe0ZC25GbMP35Gn0CdQrpwZ++uOTUa/BxALMIU7SHrGQbfmpgGvujJYJ9zO18dsWBgwNlcUWvs4kv8nfOZo7BCKfiy2r30KwXQ89HZ3zhblHuwnIaxsOIBZ1nkWVKZpl/LE7IxAv9t5BfDI+lXBiTGDbJQEv4PO1J52FtPFwwIjBUK0M2IxwEAlpZ+Od2XI/4yNdMyI3mQUwT/GpTyeqAzp2yks5Scq0NH6UPLEAinkxBXuWSpJChlHiNOfzBHcbfB81cjJY+qdueIrQcNexTFfTXpWIAAO5/WsFRinXK4dwaK3fa+wf0WKs+IXFlfNpeLrWlpv+XOGGy3h1Ci0k8hbMghVoIU48h0CSIqKvuAPJ5hvoYQab7Iqv0+Z6mf/xELVqI+0QdyboAoy3FtsO7YCXdTRyVl7gSWvw=
    username: AgAxT/tbGYrsoXVlIXoRL+A/86XqwWPkc6ymXLLMCym95wF/yqcG0mw6pXWTToyWy6BoXH+FIPujENmo+aXdwaveZtgRzU+ghXIj4/CsgGlAv9Bhc5JQq1+6dpPV5fT+0Pinr2NfjMIxpt7+APZikftgSdH4+bOyUqqC3uw0F+vJ2dQCXS6VrjkvQzdtxpkd+Gej2oYdEaeI3pWJz38oU94/RZwQnoBNIfAK6KriGcQn+hsAOCLpSu3NhZj/SNmiVNMMqIdEi6t2IZH+b+k+0cKWqhN9rAygwunkOTvWfAcny8sP7Z6Ivwk9FB9uZTpmKcgIbI2O4SGcJ9wZg0Q3Uh0ViuKxngo5pIYiktlm0gbG1U9pul8kN6ETw8yH5+grwhDOMdIg6kIaaW2tHU5ees8wrt88b8yv3cBHKINDs4CJdVw9KVcgCDzss0kji3ZQTwOkYnei0AWIAW/xseix0lAav/2+Rv+ahF/PLBoIwBSoJ5x0sGHlN+vQ1lcarywSfSfgWVdve22B3KamHaQGcb3RzfGSmPmCGIKF0vGUoKZMFoB0zA5xzGbrgHozFqUlS9ADegjEHUoWNbsHcEXIlvkiFCXhp1zrfcNWmyi5SHDMUz5Ej6pKW2AcC/tbXoh2UxOoG4/Dh62i9HeL9vGdDDX3zTrYLjDcSj18/B8UWDQkig8agWMjoHqWwOqCcl3zswlxpXBn1g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-trino-credentials
      namespace: platform
    type: Opaque
