---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: trino-users
  namespace: platform
spec:
  encryptedData:
    admin: AgBxQbtNYWgzDV68WLGvz3Kqe/eyZar05Rf90aRmugA8VHGA7Gr6GLcb2H50rljQVZ82bMQUwd4DpGcAtMpIivkOjLdtjs6Od7n71PYglKnC1EkXnDNkuaf3UfygPevrQ8D0ACbeiEfkDtCUkRIALR8BFE97vXOA+qTRlyybP0ho/qwtGKWpW+prfRVaUwBFoLkpjy/1Tf+FW4H149Yx8S4CLo3lKHaIljg7Zm30nuuY1OyIKHVOZqFiayDdhnB19TYFAmbZOEBqGqJZkNgdu/mwL75U3oqDI51UQoIAQ9fo70uEgliiF0chpmDbq0v/jldq7OVlbem2TFCw2FZv+wF4TrSsQtFLDRNRnCYkUzhnNFxJVd5iOYpFbRrvOkCeYK/83IS2932bS9ZJJzvLufYrhQvWw7ErjYEBXURqGtlwRi4v8o4BhvP6g8CO1jRU03f+K2oAisvY9SNSmUXNPMRkd6ujBaxc9I/BzF2MpEj23q4Vul2YjD+zsBobQ+co/fX30fq5qdYmDpHWK3OlVmKdjVVPK3jJmZqD4NOQESFH3M2npfngkw3iarE4yKJXziBYvNYgTQPUPalV1Jb0Px0tnin6zXlOY0Jn9MfgMXaN5vTFpqJ1xwbadF0DdZ8b1QTrr8l/0vPuLgRJ8RBEUrY7hV+8AIYszzruY9IKS52K82EPVSDmGptYAKz0TEvVu+wQ60lDrKkVXe/E
    cockpit: AgACHyg9gTwJINWukHLAv7v8lmAYXnsH1V0whmEleMBTUEJtggJgrU+2PSVEYTwmj6ItvOkQlra3F5c9K4DmZKv3dUN50oJ9cTtIjAj1kyH6zigVM7/+exAz0myfSueP7WCxgnZdXND0x6PF26ZlW5C/KCn5yDb8KGTIkNFm3PwUHUGFzFuLg29pio+xORytlzFgVSefRkSkp9Hb7Pnbx1kVmGd6515hveoCO8q0rEBsWg05VguiWSEKV/2VtDt/E8ogrj1503kdf+wX7nUyQQ40jTydbJw+OC1amJGXUezZS7Q/5Cq6Vqg3KBKyhucQnK/35X4n1gxoTlCeDGNzoIYicWuFx+X7JPYlwQWoOrRzEBBK9bZU2BUoALFJd3ZprnDBOBbWmRkGjmfalmRHT6I6R2rhmERGSQ62D6c1wLcCC+BUu3CcHSkAwYgGNEKZKUbFP2gmCeiszV/+JViWu5r8QxkuqTRKhpF0WSxkkIJJdKfFASpxXrOKoHLj6DvX4RYSvTkbtWdKPGnJMny5dTATn+K4eQw+qmC43APtGiQnsiuBUzZXFk5QAqRpMH2mkF6l/G5/Wslh3Pjpwpl+Soj9axisXUfaqwa0g5tUeOIRjQGZJI0C6kmIxLhE6DJQxF+fX/GdW56zE72R0yxUFUTXYBxlAvME7S5vLbAiNI0Se1Bgq9TOnhNK7/eQqcOdStP4JZLJmhLQYdjs8w888A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: trino-users
      namespace: platform
    type: Opaque
