---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: my-trino-credentials
  namespace: platform
spec:
  encryptedData:
    password: AgA4XpkNqPfltxXZ4NtC7Fq7EgQ4kgmZFw4bddrQccgTvs+zLO9M6wUpSr+dNqzOVWzEBC1Dqk6wpGeCKOv7o3/HgFL4SDl64ZjC7/LD9UPBQxEZwznB5723hKv0a7Hx0WpQo5BsF5uz02X2iddYfYI1USPH0IWLWvhhec4SDIA0p3LkoU6JQdfdcvgmtFk7Yzzcgi5hJyUmplZvSB10fEV9yIUu8eZCZ4KAnkQFrXEFygAiQPO/OS3Y5JPSG2MpLAwsEXYkT49IsghtpPzgzf5Vm3NolBfaEtfWmzb/yA4MJqrTfJLah9a/2VDAeEZIQC5FDwxBt5tyxP3/2Bb7FH/6eeP3fBz5ov086E72lU1XW972FQq/JhiWZojTViKyjrqtMCFRVkHoAchiwWyDiGcmv93fXUYfU0aDGd04CKYbudQUAs9tzqgMufStsEyrDDtZoSnkwX3a3H10WJLNAgu4V3uLluNRqh+qTLtI2LkWtUmWOX9wrpUn/ZsJkly9r7TJEBCH+GyGp+Nz59kMW6PxM3g9ROpZAdUb9GSxPBZJ6h992DE1SLkZpshdCO8Kx8flGoBZ5+A5r4dnwOibQzbho2kgmlUWwcRGKnLsaHCwFK36TyRtfARRHBTFUYz9YT4Ls2iz/QWYN0yVMTCpnMSUS5pggLCPxrwZXQG/5uiI+tF5L+/NqPgKx/7xPl4RZTTzY3GWB5Fhuosk
    username: AgAnxz72BBxdAhfp5xAx1zACdEXYhgNwKsJCjrnD4EyLnYftIZ7oFFJDtX5GKGeUDjspt1HwkTbCprlpnTpvx+cE3bOYKRvsaj7/bekf24nGGc1GVgsXPCYn2SHw+koZH8GrNTUmKswTAJRZpTxlD2DUvDWa3jRSCZILRMAD+mJUt5W1IARxiuZmAtxx06hxaF20spfX4/CyjFb0vC0p2ExGhDVI3vQZMVd9V92eoMw7LFKWhOrKFnaFl76m7P3HxM5VaB6bhKpa649meHJguiI//3J6G/VBcLlQ6h+0xcQkmkW1oTljgcrM639KQXltPM0R8YWUnXMitCEKRd96kQoQd7i/iOuBVFS85bAwjMz/P0MGbFcWtxJd451SQBBBGM2lf6hH3XIe8DmR1D3Fg3WJGzeAFUeupDl6VzKPKul9ZUhM4gYyLVnCrMC4KNpR8Ac8b2wjb82UoVcsyEk0WPbuvBzU7g/j+U3tPX94EIwX4xcQiGv3OMN8YZw+tP2dScqLLgvinL2QGeFMVifoFDnDZtFYJC7LEzphYuH3BjlWmTg9TUbHyTEiSnQmewUMxuN8RtvvnylSD2P4gRM2QXHZoD3WK1DTjQMuFLzy865ZQ25+h7eNIzA8XKRAOaTdGmopsgOyAAwoeKgYN7+kU729gbScDRQV+wkQSlSPq5ZPd5RtsMvGK2+Sz68XJkhSqcTAtM2jaQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: my-trino-credentials
      namespace: platform
    type: Opaque
