---
apiVersion: v1
kind: Service
metadata:
  name: entropy-data-nodeport
  namespace: platform
spec:
  type: NodePort
  selector:
    app: entropy-data
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30808
      protocol: TCP
