---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml

configMapGenerator:
  - name: opentofu-airflow-script
    files:
      - run.sh

generatorOptions:
  disableNameSuffixHash: true
