---
apiVersion: v1
kind: Secret
metadata:
  name: hive-postgresql-credentials
  namespace: platform
type: Opaque
stringData:
  database: hive
  password: hive
  postgres-password: w70lpAuF73
  username: hive
