---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://git.deuxfleurs.fr/Deuxfleurs/garage
    targetRevision: v1.3.1        # or a specific tag, e.g. v1.0.1
    path: script/helm/garage   # path to the chart within the repo
    helm:
      releaseName: garage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true