---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://git.deuxfleurs.fr/Deuxfleurs/garage
    targetRevision: v1.3.1 # renovate: datasource=git-tags depName=https://git.deuxfleurs.fr/Deuxfleurs/garage
    path: script/helm/garage   # path to the chart within the repo
    helm:
      releaseName: garage
      valuesObject:
        garage:
          replicationFactor: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true