---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://git.deuxfleurs.fr/Deuxfleurs/garage
    targetRevision: v1.3.1 # renovate: datasource=git-tags depName=https://git.deuxfleurs.fr/Deuxfleurs/garage
    path: script/helm/garage   # path to the chart within the repo
    helm:
      releaseName: garage
      valuesObject:
        garage:
          replicationFactor: 2
          rpcSecret: "5799da09045e5b2ad62bdd658aac3f4c1311bd2c92af32a4e8825ec810920063"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true