---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakekeeper
spec:
  project: dbt-openmetadata-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: "lakekeeper.github.io/lakekeeper-charts"
      path: lakekeeper
      # helm inspect chart oci://registry-1.docker.io/bitnamicharts/postgresql
      targetRevision: 16.6.3 # 17.4.0
      chart: lakekeeper/lakekeeper
      helm:
        releaseName: lakekeeper
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
