---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmetadata-dependencies
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: dbt-openmetadata-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: "https://helm.open-metadata.org/"
      chart: openmetadata-dependencies
      targetRevision: "1.12.1"
      helm:
        releaseName: openmetadata-dependencies
        valuesObject:
          airflow:
            enabled: false
          mysql:
            fullnameOverride: mysql-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
