---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: default
  sources:
    - repoURL: "registry-1.docker.io/bitnamicharts"
      path: sealed-secrets
      # This uses completely different tags than in Git. Also which app version does this point to?
      targetRevision: 2.5.16 # 0.30.0
      chart: sealed-secrets
      helm:
        releaseName: sealed-secrets-controller
        valuesObject:
          global:
            security:
              allowInsecureImages: true
          image:
            repository: bitnamilegacy/sealed-secrets-controller
          keyRenewPeriod: 8760h00m00s
          secretName: sealed-secrets-key
    # TODO(@maltesander): This should be parameterized with customGitUrl and customGitBranch parameters.
    # Currently these parameters are defined in the demo-v2.yaml and are
    # not picked up in the stack - What to do?
    # TODO(@maltesander): Must be adapted in case of release!
    - repoURL: https://github.com/stackabletech/demos/
      targetRevision: main
      path: stacks/argo-cd-git-ops/secrets/
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
