---
apiVersion: v1
kind: Service
metadata:
  name: openmetadata-nodeport
  namespace: platform
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: openmetadata
    app.kubernetes.io/instance: openmetadata
  ports:
    - name: http
      port: 8585
      targetPort: 8585
      nodePort: 30585
      protocol: TCP
