---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: airflow-secrets
spec:
  encryptedData:
    openmetadata-airflow-password: AgBSkwTaftNOJsVE2xZQ1CuMk8eygPDYnBmM/oOSwgCvOa+wAX+HzauiXXLI4/DarnEu+gwCwH0AcM0c3wvoKxoTFCqhd1iWd5hYqoN3Bwc/hAAyu2j514thHUCCjBWJO+y4dWCuNewOrRdgChsAwMMcXSAtubzbGKZ2nXWZlh0HkHuT8r7+vcbSrKHQCv9hX9RNIZr/8n9AGlr8gEJ8N75MIbX9Yjj4l1C21rMfVTrDdOudCJwkAGNapA4HoCkvoO37WsFOWyRrD/dKAZkrHk9Ak4jhyc1w2WdqHINPhbfKH14ZZOTPFCtcK49Ygs/M3az2cVOvkCoBgxcQCMS8Ue+aqAuITOZ/xHJAXI8SWFTgZyJd9w1CDi4WrgE5Xy32RpmOigIMXtf/hBw5PjZAfAsCpZyCfCyLPj/utT0Vd5CAPyZS8uD5wunmQNL2+pLceRIsQLc7b9CZJRzS5BP4pr50crznut45vbS3ddEiXJcobuxsaOetrbbBab/4kdhm15D6dEEzVZ8VM8f06Bm+QyF0Hxtd4fq0gU1Z4n+CgJAlBwS/Y9seY/la9eB1DoVJ4iB4aEZdy7nziHs1CwCdrgDDkgc3H8q7Nk9bgh+tuZ/CkaToOYR27hgg40xvqjkjDf6bcwkuPQxiJflz2BH0a4K2/7SfqR8fjH8ORlJxHY3R8aupLBfsYd2HPewuhtK4vI7SW74/Pw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: airflow-secrets
    type: Opaque
