---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: airflow-secrets
spec:
  encryptedData:
    openmetadata-airflow-password: AgBa40ZizyYc0JqRdoMzg/OARh5FTFhLAMDmB7wn5emacH2gZ1USZMh/+zxEMKU4osYhXB8OXzd7KuRq8K+VNTbDiBY5jPiZXjohf+kM9w9DZvYMqp6B7KySAt5okFsMQE+JPWfgoQkR7p8whGejEXgs3BeBHRvW0MnD88O9pA26YOBFHvx/D9gkYI7diSQKd/GwtWapwHNgcb7sC4QvKh9L2oJ0exQUy2nYNv1M/FroNPK9YbXy1864wHLdmMFk+9ih5eMjPXOyTnDJu8kecupebpAAncnzNl1RweeP/2XurcPfI04fIicjCqppf71cBV9GeoYo+MaGN/F19Hy9MVVqpqKcRqG74JTven5quD32vCaXaXPhyzrFXCp+CXUdxyuVRhnsRpQlVMe1/ZlNFVQ5fM28aUaMLH1YOU4gEXR1IdawaWrvqXiavl4kfyJnrEfc5/9hCrt7ExzwcJkBZ6flIsOfh3iocSr5Az8FbpyEnwQ9FuE6B7XXAVPyhfN3OlG3M+64tKUfP9GQNgNtEDtKsFe2fd3BVud2xB+VdR0GX2ljnvqTFLuiL3mxT5nwIaiv2iaE4Mksr8OU/8KTYpcVpL/dk5cO8Q3jFL1c9RRuKnUc0XyxpngZAE2+5w7lKkuMkkYnoLUBZBlPvN8vo39Rl/qAsXzj60Ub1BlBRU8m21kCvzc5KU7qrKRYY5/T0cQNhA+dJQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: airflow-secrets
    type: Opaque
