---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgresql-openmetadata
  namespace: platform
spec:
  encryptedData:
    openmetadata-postgresql-password: AgCunzd0CXRtIGXMPPhkCNdUYOEHNB15enRloHHNGwjwmmCoPJ+VOu+tlw+z1qOSpJHGwQWWfKNU9azhz+kYld4Y81q1s1ZBzRGY8tVNfhSvGOkwOhh4POmxN5usW0E8zZs8MnFaA9WmDe855/+LsVmasQJAgN6rtkgG8DTaFOvkPZiwvJB9ScectOQDoRuR+lNQEEdDx1rKxYmw+4UUJP9ZFNYTwbqrCsaIcxvt7hxt+fuVR3rYd19YUv/rdT+GBwDvr+4ngU+0YgE97qVfmeRjyXouFPg8ONod+ZGzQN8YkHIZUhdHILwc8kTK7vxxTOl2lkZkpDSW8aBRu+7SHwFy/gHLs3wMTD6IT7w4OwSyNm35ILBgIqW3qnaKhwSejuMQtn3y8OqogvRgkZR0eCuNcZpJiOGkuffvGjEk4IlKSH771H344CMAf9wGRQDJqQ4z7aTpyjSnaKFdJ7p/ljDOrRfyzxBE+XJVWkwZQTEy9G8MMHzdu0Y9YCw5QlpGYjoJvN8HOU/2aF0tXnXHEhkanYDsNOWbGkwAWEdmvj9KrNfqVo76qZMPZgjQ7iR2EL82Mh8DqzImoOcncjR0Yvn5lSYswm0h7QkBlTtTquGydWD71z6THMXEFnyzvwGT6pgjtPr19X90YR+P2i3luQz2hCNOsLp2Bw2Yv22SHvvZSeldR86c0CCXvvmUxxG1htVBFqUBbFCihICJ25s=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgresql-openmetadata
      namespace: platform
    type: Opaque
