---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: openmetadata-truststore-credentials
  namespace: platform
spec:
  encryptedData:
    openmetadata-truststore-password: AgAvA7n/jv0zlqz8x4CVjVVjpF2ZAzAsNNP9mpNDDZsrWbV5ND7qIEx/7E+HKNU/yfj/Um6309abgB00U+JVQKu0dBPJv2OlfBIEHpG2a7dhTRRe423k9WSH4ePom1U4ZhSGS5xyldPVk5ZlD9xMu2P2O8/YYuGryIoxHxZ233xGj3FQMtiZGTzvE3GsQEQSiKa5k1pF7M++kni/Wdht3IX6UVzCXAFt7pvUgRBmPId15CAOZA9S8fYUsM2bw3b/8/m5wr8BBQYm1TUfkCJbBcmn4NvAPhUvc9ooN1pQuQ6DG5/cdzet7rL4lcBrKN3bTKgEJnBbqhaqYB7p7LwqdBzRPNNiGRTM6bKHy+lGBG7yrNjhCBPFXwvpxLC37NBswY0yPR44Rw+T/HML+/DtFrpk9jrr0vdDlRTAkDeMvrOZtA6i5YRviGLYp96Xwr/nWHX6K37alskw97pFRXmWIRtjRxZy0f6yWUCUrxE/swvS1Rnqmj6BrSBH7UBafJtfsPRWQPHOBOSepUzS6t23NO14pkneyMqBmLFFH1I6sQXvGXm9lNgcBoQwR3lsp6AR9g9czCuiheywGB2IiM1cCmHebkgo5Hy7socg5zXMNyuHsYZwzizrxaHJNNhlbh1jxRFkjdT8puVQ0PZj0hUDCOHfozA2EZEQeHhef16XQuXBzkDTKid+s4SBmmFUbNkFA8A=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: openmetadata-truststore-credentials
      namespace: platform
    type: Opaque
