---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mysql-secrets
spec:
  encryptedData:
    openmetadata-mysql-password: AgAddvWEpvNX96pO/DGvYwfWXegbbnceSIHk40tDsf4X09Q5sXxi1O9GWFuXJAl9YHrxZ0HbvQaacYGz4zYgciJ66oHCA9P6sM28kshBhpG+YmiAfzw7btLddd5ke9cddj1O/Zf5kXIdRvi3SLO7BdlgznDeLsiHF1tYXd+rSgSN6nO0ZTuDiFhzl6b/P9QDTQuStLm8t4Q2Kizyyh//ejH5MbQBmrhj6pE5UATzXjabfS79mEEU05VUHUHzEESaV2cOmXlwebNBAk+/4cS3AGgZBojFaFlxJzxKC0sE5NKe9cYpUXKgHM4ToFwOpngSAZPj8gbx2Rb3C+NoGFnxnRDPXHx48phql4CsW7wV2vJ7e/dvlRp+BzlfAEK6SmZ/DLtxGBnAavNCRzVG6q3mFt7K0U1Qwj7ELc+m10STKMa4fBEF3xnH3Hs9ZN5Ou8UXD/PIFn6aIWUJzPMOQgv5xfMIXMnhTQJEH43b/A5a3xSpOH47oOWxZ8WuuK9lq0EUB3BNm4lM7r2GJGJ6MyKtJIC0Ajc0FMdjNau331LqzeHr4hKkhHvzqIBzsjP7uVdg3/uRVXfNjw7Z5J0nzjVjxaqQHPnXVQ+ASsLK0GyDNvS1jmaAro9+edqVVd9OaJxdCkM/ZqRe16Vksg5BgsDhSQttDjxcusIqlqI04b1zy8eBxKUDz3qtV+DcjRoKegWMkpfkOIo+osQBhM3MdNCS3hmgH5yYDYk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mysql-secrets
    type: Opaque
