---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: airflow-mysql-secrets
spec:
  encryptedData:
    airflow-mysql-password: AgA+GRJQVY172tB5kqkbZ7zZFkPC+gQXcTaE8NHW+DYwXnOb9CAzUP2mZ49/KfgvSL6B2si6v/DrVatjRXyPt9JBoY6yu3OHia48FEyV2JvQyTvugPWO2k/fcUAfUztrNy6ZWaIuQ/sio+gQxQv0v5I1Wx9C4Vzr+J61NgX9AHYcIj/WMGMoT00SB6kUeW4DxGRHtQWGR7EwNY+xbIBrL+beiYn14V6juVFvRhPDLEkwIUW7fZzOCEz6X1n8mfxMSJcn1dcexlLQqRQNYaz0U2qNfK21fzgQ3TlLQp+kpZeOVbNiHWMBKhpuAGdSh9Jf+iwNlg5dt2bw1cREwwwdFGbA2WAA5dtryfyXao1ABST4BLGcQCskIggvOvGwkrahRi/dDnttyuSajNZcC1OkR4GvGsHuWBr2WSeSLBSIe8NS3mjfb1kTO4p1tWm4EepQSTQ+XkYHFf7uhl2vxTVQPIICwtJ+KAfJYWO1tl925r9pSYtR4um0wu+CT63C0wZR8Q/eZdg4gYFOTsYzf5JWccv1quR8idoAKe1lHbcx2FEI3vdev3A2eEbHvCnDEu6ED/jCTpZtWMNTj3zwz4t6bvxohvACvuDyO0DYYHvCS4LT2GVfjdNsprqxkFxxm2j/Remr0MUZwveZvU1kHegIpFCmcuA0ffgZNl0uzCB5W0p5+XB2TNrokhfnlrbgkeOKETiBSG/mzkhvhOgFrFU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: airflow-mysql-secrets
    type: Opaque
