---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mysql-secrets
spec:
  encryptedData:
    openmetadata-mysql-password: AgCmJ3LBVmU2RH0MR3oU9Ns2dAMT2bkwC6RquXNhnGxYdM7A8X1P9YIWRsf9RSCmzMHgmMRdih88fYRM3oFrT0hrHbm82r2ULsbYm6AwYjdesHPPTl4rBydjJhVxXtm/VYJyFSZ6Kn+A3V9AGvJSYcQ02FEvP1BC2ehK5JqyqNEwyVxO+aXckM29oliftP0nC7Y38kQW7Bmdpx3IHLjP83FfsFG8QcvK0RZBz5S1kTvw6K0xQvJ5eKPq1IGl/ilAOuZuZDJlk2HWfUVypK8WG+YqEyqWrgDRpOwg4q0hPkyQ3V1sl279FWw3O4NawaM6UDt9X3Et8EQ8bunnMq3GT6LDKH9trJpmy5bBxiE9fURjMidnjVDix9JNApa2AJVUZ9EKDLIFPFVofiTOoC4ETxfoC6CWcwIGGKfJsQWmINEGLKi3JoInZPHsNa16oDjllbfrtmWrkvaGtk93RQyFr0UY+95DU9q9sCCgxf2dANRPMgLKFAXDnhwp93CUU7PBtjINLRk9h/TbGtRVPlWF78Ip6ktgUpeFNUVsx5vJZK1+r4NqEwg+ZS5PajmvbfGUFDI04dpY+ARbRoaRLbmFBkJ8/9CHfZYn6vJs0DimwyG+dOB8hSoq66gBNtOlp3npGQ9blI139V6OoV5wALdG0636IOTm+YnGNvtGVfePNswzgjL2C9Eb4988zBEpABmMp42jNYQzKSDhq/q8HZepx2vFfPCREHU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mysql-secrets
    type: Opaque
