---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: openmetadata-truststore-credentials
  namespace: platform
spec:
  encryptedData:
    openmetadata-truststore-password: AgCF2aQjBq6bQ/a0lZc9I1syLigkAgH8ChyGjULjYHjNAArbkGGGOavZb5Unf3iK4cdTFil20FBr6m8hN0teljTZEHi1KcjLbbEvvD8AQ9aI/VRQLXNkzCGjCJybFb1e0Fbfl6nDneIKCQPX2a8Oisi9wkut3VuEOiQTRfghzoGfJcjo+voF6AddYDfi/NAU9DUMMUXrrtGfNB/vPWUDNMtotg4BHfsO/yzCilqT3e9nSk5UqS7toGMnEnYHMkYgtU8Og7EoxCtzWryy5g9OfJCO/1fU/tVm7/Degr4plsNAt/6cRauiZNLVz1gUkCXtNMbtl2IwL+08asOszV19tCCMimobQ563uOlcXcbMoKQ3FK0rNfn/piCxBu6YJNJTXJ6E2mtFKUQJlE2dLwjMO6l7x/q6Tf1lA1jx4BWerFPGT9JpRYBgG5CdYzdT+O3NfgB4FZjhafD+GmVdFpTPoVUV92ZP43Md+waqmid58SeSnbPVhyxDzOAxKJXcq3gVaDhVhMLffC0O92ljKgWzgd3T4lr8oM7NtpcOa74xwgBxZqNK3Jj636thIJN3o4qfxn2kuTanVi1bTtJ7XmMvIaW7xhKXkBJu40seSr71hUJgnRDvDrMvYQKxpPG5NZVRna3x9TLidC37WtFznE3MERv7uyGsajNWktTCIy9CrYIQ18hkFMwlq8HrXGhxVs6DscZKorFwhqUsCw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: openmetadata-truststore-credentials
      namespace: platform
    type: Opaque
