---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: airflow-secrets
spec:
  encryptedData:
    openmetadata-airflow-password: AgCqBHNjaZkSINlSNpIFOCaoJQuKL3893PUHH1f6xHwCxSJ69UGE7EY/Ti6usGdRqJrhcJIocGLJDA4nrTBu2JzshT88LWERZ0NnEX/nV6hSQlrMdHfQFW8czhLCZKuzJzT1B+nnbYzAe19DYViWOndeL66mTlVi18bIXj0Kr2Kzd6pLGZbdmagjXRsRaSTtQgnGzAEDtW/ewe7L4cR344xInq25ZtCT4/94Q4rhhKzZD9owq0cU3z3JRLYKQtB4XDb/lFKq7Jvgf5PJetCKuklhxMnrHoyK8GNimofxioXfJ8sthavO+iQNlJ1ELTU/4QDSeqwISPt0KUkpfmI1318CFsM7oBfauM2vRVkVP8SL+rK2oHKbcaE7PM5EPzuQRNLcWgsvyNHCmj5E5VDyuW5OudXZ/euIcOcpTFRFsGetEERqemgsGdJF00MyK2y36ydhUK5Snq55LpozOVdk9LwebLorzHiG6Jjg2nFeyuhJBZZdEsgvwNBdDtpJVeC8fdhWQHbtpBmTQ9wO4Q1SfDbF8Oa41YHWcpPZ+oeqKJ0jve+fn576s0fPxhDjrhLvwhfSECiLby9zRqbzULVdrbyA9I4MZXcJidIKBQcxQcGXC4924qj1DOl/OVG7NnNaPQhaZ8Eqp06LFfvcc6Wc0is2oZPJWGdfWeAUMgzMEUADCpsh3Qit2URGfZVmeLtg36Qq3XSRhw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: airflow-secrets
    type: Opaque
