---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: openmetadata-truststore-credentials
  namespace: platform
spec:
  encryptedData:
    openmetadata-truststore-password: AgBv3eje0qGWP1PivAvAtLoZ0UigTo+qlmooaED+Fv+0VEeBlZcIWaaZYIfUlFRlXj0keS2E3bQgDZzelqppHu2uO6Pan1kf3DEPUsVPSMF2qQ6I5XJL7dvvzEbcbSlz8qvhC/anu3gDG17s4aTo+PSwbQ/9Ucy4YIfMvN74NlarSDp9tWlYRIMhTCklg5QroE9di9810g3VCp+Fdet7yLnHM+vnFc3dRE3PEGVX+lAHYfyTnzlT1NdeQetcY2L7VIvQiPsA8DnszgHNK6SPubXO3Uy6Y1UeesfaGFVjYAd6kOxprKr/56Z7rlYVtXSvIaKY3LOia8Q+d/gA0RaJ7C4yXQzHAYW7g6eWh0x0bA47g5Er/ucmmt/rYgb5CpOZXmm5hHL9ENoHyDf8og9zcsI2PK76iWwpjRZfY5byemb4H5vAq7BPzqiYY0mGQc02QcIfA6opZHRwLMkQN3hCrA2weylD2oxsjqnJltbMEptJl9VDaDP5NqhgrinlqwDm4Ue4BETYgle6VT09qoTr6sPAxcLRt1QGCig5cLna1/NjGWWtv/wVSWHmtihwwYP6EuPXhVXMAk3HLY6hCHQCkApixiPUNfM4D7z7RNtKiN1WM9K84LH+S0tVcY6AA85lR+ZJwbqeHs712N3gb4R0+N5PWnCLZ/W/cBd6h+xoNWIQQQQm4WZfUe87xaBO65hJqkr/I7z7d7EdfA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: openmetadata-truststore-credentials
      namespace: platform
    type: Opaque
