---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgresql-openmetadata
  namespace: platform
spec:
  encryptedData:
    openmetadata-postgresql-password: AgAluV8IsxGfA6tPt7RwnBcM/LTXIUUtijmsGCVV0g6RAGTynTs4prmoj9wLkIiHPFmWMx5pmKzseRKnu2YcajcEc5iHh2MUevD8N9PIRiL6X6VMDfePeq5pfZom9g76CeQDYVwpOyPU31Yd/W/BjPXmAm1JYNM3Y0l9RXPbKUEUEox4hB2+Ov3vA+KKLhFvs3lo4j0K8dXJHwnCIZGe5IGDE9q0HOgWnHSGm3qF3pAINXe9gTISVVtPEnpzBYJ92TgAcbMYqZLpcsRDs1qY8AbCWsaqlPZ4Dniwcn4HgXL80hQu06kEKU0Vtitrdkzixc5wHVjJFP7y1EIszW13xCL4QRB2yEJsJbSSFIb80lZwypiF25Fg/MTbD184JXBQ9dN4XX1BRn2StbtKLGzPxowzCvGCeirHG3QDLUXB33+IjADgAVFLoTLFHDUsLPck1tO1erI/lIC0tz/6NiWH/b7qOknC+xyILPxiXy0kvhn8xwxGQjMfQPfLJtIqM3r5aidsiBRHult/xWBQAcw7R6bSQgxtxbwcHkVUrfnmAuaS+F34CNKocZTJAPJuJUobrE84cFduUDJNRZHMi5avkahpLgEKikegPgAc1PjdbEcPcbjlJNelxm6i9H0FkLYc+X6nhzHziGCNpSY8+gp6RzL/LNmm+i34oTtQ+oAku17qPwHUU20lGuCQtWW2ZDt9T9CdizPCWo2a9+qSijU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgresql-openmetadata
      namespace: platform
    type: Opaque
