---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: airflow-mysql-secrets
spec:
  encryptedData:
    airflow-mysql-password: AgCnBHT9ALHDhTG0mMu7ec23xH3mTkPVADFhRV0u4pqnr4igfs/ZW1IOdRdNbVrI6FsTwQAfFAVFdWjSvMgY43vJuhMyxaWJueaooi6HNkJlThgN5fAWsN+XIlyaxIXUSkdkztsKogsgQMyBlqAZHvbi32woy7CL3aFxdq5dxUUcjLzQXES3QoZyxlICVt1xcut5dhGOkgt5u+QvS58wqBlFLdrHqQwvuRtKy5Gewh/Zd3VZqugdqRubLj6Epoe6Bl0DMAJoP18+ZWl/XaY9RysM4QYVpco/dDEKQ2xnj80IYxLIHWyg1XtkmrhS1CdL/+LyA5eOnsJfpoj1r2GwL/f7HjnRowdnhKL5g/Gt6t8QHMikyvGQ+9OvkjVPXEc+RT23ubC3m2Nh4UAMu+e1qe+fTxNLc2Zq9xGDu9ooqaXtiVx1IRYmMrpnDol+z43S33iRrOAKOuH0LmaAsbYXkoS/2pkI6nX5RCx5OapWTdbvnHsrI7WylC+u9+R8VGN0k/766QVHXB53xyVJLoGuJkKGxAQ8+/L619qIxzwCs9r+JHBFUJMM+lT5kUw++rRo5/po5O+1PK2G5uGA/FftZVQbf+E6JkSC+lmaaYm7TVu3ism3N0rrDq8okPjaAdUA+IZxehXeY6JPd9pFKmCIvCBjFf3bMecJejIOkL2NatdoYKX0en4/s4F6aHyyGEK0UchJGm2laDeBDRDqzfI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: airflow-mysql-secrets
    type: Opaque
