---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mysql-secrets
spec:
  encryptedData:
    openmetadata-mysql-password: AgADTE4Zvn3l45pbUijF9mcmvhrrlc6mNAfDlKhh+TWII4fE9FL4OQOmtY+6Y4+F/1zrXkHuZ7kWuDJUGLVnp7cTNxHuw75+IpdYZtRGhscT8PZ1j1pg87C3OAo8h6CFlY1xmKSmbTazE68+C/aAlxQGb+FwuvFgdA0JJ986Wn8I4TUIuAgIGlmQgTrCBO+tccNI8OsDcwPFKjOzlD0ccXUp0W2imShBkfDJ6ELlQMDmhj/7Xf44/1BVpupT/pR/1oQ4njrQSc1r0R4DZ4U1o8ijlqGFQKK39WnAqr9asdnOdMKZ/s0P/eeiM6KOlLtq8WvHiN6jWrpInMvEzXeANChShRPUfvR3xw3qf0b5B1p5BAR1uTf5clzD6T4v28M2/lQ7hJhwaIxaoOpjP4MJvmguQeSZ5dJnBSxGiuw1v7VRCyMiiuNRHNa/EcH/jRPZtxmbXOForDqctAh1hplQuWeP/WOq3dODqKVZgJ3M19ttwh5rbvMHTCHFQEObq/IE7yzOjX9t/vLzm7ld5/gnkEWaE9rS4JPxVWzO61N9hHBZWCGhN/0m0d8tgPPcG9pCOpt7LbGxCay4rCS1sbvFJZZrEhjvFZSPAbEMY5Nhm6Ka6z2mmOwNAvjToh/fE+FUn6UiMIP9NqBIIeSv15tD6hfUp1vYvjqdyGENNTFxo7s4kFk9NbiXc41bwO146xQ3FlbhfDs2cNfgXTw2OEIl6NiPafgwE4o=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mysql-secrets
    type: Opaque
