---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: openmetadata-opensearch-credentials
  namespace: platform
spec:
  encryptedData:
    openmetadata-elasticsearch-password: AgC4FSVR/yLcpcFNzsIFTTvq27iPi6ozrLIVZcI9nUg+zIKQdL4+X29T1TlDlt5B+DEkfJ/2dY9MPHR60leIlyZYO/nYjKiKMRkja5CIRRsu6qq0AqBsfSwli3GR7gDAFE1HNl8J4T3PFlKOhEDWV81maZpkYmK6/lpFe+g2RBBNHEyH7a9NxRzk5TtaDy09RHXTN8IbuAbbibR+mUDuu6is4MMg3Nm6lBjQkJEVSVaE/F9X+qlUJQHITU8Gtvy2OmUUfFPASJT2xzynfl+Jp32vbbJvA3JSlsgA8g0XCicULSv+MAMAiF/TgveDRXpClX+wXusSR8gDnNzNGP3ZNdS4vNd66YQ48PwO2bu1zK3QRCym3nqYG8fTY+zNet+AKqUhVy+Dnb9J93NrN/f+q80usnxn9eC1SyiiodrTc4fHDzOoLH579dtSrANmPbbg8utV6LKGofUxrgggY2tM8et0gGiUAzXsMDoj/v4pR//aw9L7nvXltrX5SlppO47rRNeyz31lqXveMoZDbDwfY6Z7cQtNGUBu6tibviVWpgV3OTTyRs5u3Wtc/UzmFHX3vjGkc3f78swo2ZCNt28pW9lUEivkSLYS5lFvYY/iVmhsHzbSQba9ln8zgmEPKvc8kwH96tQH3lnnk2Iu1OL0KltRtxTI7DOBxcXKTrayZgnWMzzR3orx0EuFV8NluvujOAGGVl1px1ndyekv4V+3hyTP
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: openmetadata-opensearch-credentials
    type: Opaque
