---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: openmetadata-opensearch-credentials
  namespace: platform
spec:
  encryptedData:
    openmetadata-elasticsearch-password: AgAvUtbud/vE3znpeX2BO11KECwvXKhY9LbnxDMGAyER2EM9AdSXfX12ntZyrFs9iceoJr3LThOWJ1taWy52pxY5EKsQ8yfwIHieXksWIuALliKrVsrBwJHJqEFgfQXcGbaFwRJb4xpS6j7n8y9P0o9bTrqA4q2MCjH0avjQtXmmPlucpi6qTnD5UUt28J00fbFic/AHuL2F/ALVVbE11Uo0BI+lNESO1ishQPBujWYuq4RQNsJB4+n9oF5W5gPutJNIHuKge8zLBsW0dJHH9DtdYYejdQXg90trt6H++yWQ8JRzPYpCxowOf2hoDi8P5MiZL8LBnHjQbbhpzCRjTp+KTyIitNgDEfbHq3mOb1Ts9a8elKDOSe7JULLSkbHJEKDl5SYxPed6X4IHk8ZR8nwDyMVPATxxrzJNK/81zgJDw+vaByJJyyJhIvO1k8eP+AWSPUZO+3P9ZcftvYWiLUPD1qiaf1wl9nryRjRe3C4CaFBY6RliIRkVhWTwLMOXaNmJjD7oC9NDA7g/madx87QO0AHJE7aJkpKn4OKOv8O/yc8d3xRanRzykSYfAD10Zgiw2w6K525EduL8tkvahVr+lhq9UG9GRqhLJP7YmTvbqc0xn/a9iEmsOV0RTPfVXFzYiEuGnop3d3Se33cdqjbGuXoY+/xk0vqNJvj/fWywcoiI57SFSmuQBWIq1+WlcfKs5DyFweLL85TnEhvVZTZZ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: openmetadata-opensearch-credentials
      namespace: platform
    type: Opaque
