---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: airflow-mysql-secrets
spec:
  encryptedData:
    airflow-mysql-password: AgCGGu5KNhm+UUYOeHrrgFCif94PxfoOGWOk8dqfjbTUhDr04+2gLQmrsqW70lcGJoPwGKPCBDGU/v0qBYHDY4iiiIYGaPttWkwT28Z8QT+PZngXvFkSPKZGwdcKqaMCaJolitTkfUmUDi5LLRfKGZ1oD52thvKNzyswexq2PSVfLhM+qzh0kyG59iWzl07gui/xcnlP1rUND0O3ilAMGC4QHfIY0ZgsdkEiG8X4QDwVnzfG5WRMFHzy/rE3/5dKmmr9T7/MHBVO/FyilD3tm5IR9LIgYhr3u2GM6OcDLUEfg+A0AwhV1FMrK1kI+Q/SPbs9G/6nqMMpZh5+yj7aIi1yHEhIn4kIyz36nMDN3UkMNPizq+YMCvTJtVq/dgskXn273MPGRzmFr5PY9BJ/IwdQ2wG5K3+tAYiWiDjUQBzdyOSn7kTOK8zZJd5Gv1+Mv9A6zhF2GGh0QF41QVB/SR2BZQpp56U42Qa2ge5kA4heTTcbLbPvNK8AopHxLDNoXbXFk4eV8VfpNxybJlHVHT3B+BDp4nogdapMEtKn2qWh5divpXsWecfalZfDETjIKDhknLcI1/CYMNdhLtypNIdpveQ1KBJ3cMnocR2ZoP3oSot/3grb5B78/7ul8h2A1Ru7kxkKl77So+rFCSplrZN6vvf2Hq2FeqN0bayClzNAxD/PlLV7AwlAVlECcMcBDgi7W4fofMA/pKYYvKI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: airflow-mysql-secrets
    type: Opaque
