---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: nifi-admin-credentials
  namespace: platform
spec:
  encryptedData:
    admin: AgCOGYSsKLkg1/0AGPzxnFtBeXDyPFy6g+ID1OdGCmZTyhDeWRZps5WiidaKxCLFnDW8Gg0lUBONP0TxAl7d8wYtimgWl42WuA5YW4FA5+0YskrOAOIIoZ3n1QWWeOMvggGkR+TIm6RMVHuZtmA8pNpJcGzc5Zlj9vGP/zOz2D20jSv1iU3U23yhwaLAAJT1ri2NNYQ3fHyFHZc+SnE9pjfQyi6nLsN5S4tj0sXiYuSjazz++2Is9gjv6X2UEwYf7y17DWNwkzqMV4KQUucQsXjpDGXjjdB03SB5iwoxyL+ktYJyMonnILtjpMmAzJplgJ4UKBKhdZ4DEZ3SBruLxjDwNiGa18f4nZPtmNdLMnPSefIaxDQJ2AVPAnJ9cPzEAzOxjgh93P2KgcMNtgqUEG5/HyU3OFDwTjx+guo+WYLgcXk7pQfLZUVFpkIHe6kfAyawzv+V4+UpB/noYbUcw1X69kb7D/BjuaahRREmlynyVxBLRGKT0mVhaXUdHCuBHPexHmMzMVG5c0MoLiG3srLIWliChxCt0XYUnQCsvo1lQRRa4oc5O6a0UZ9qsGOAJTNx1g2nLDbeomhDW2zkKZTRMx2w4UfJ0Q7ixTi+JwYperclHNVfBIiS090QtNS+95+1WFqS13Y3uzyU5tEiSECzoiBdkTkKMhCGFGL8VS6nJpzKfm7hoas/CMURlGs+wpipmJAynQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: nifi-admin-credentials
      namespace: platform
    type: Opaque
