---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: nifi-admin-credentials
spec:
  encryptedData:
    admin: AgCffKel/jl7zJdHrbsY3wRptmdkkM9/eC+I2jPfQsY5iTdn5Pea2bpfUQZSeFNsabtblA3hafSi1NqvHR/nkTSSwAk50pP2e9UKg529XK/XQ87iV5tSJirxSe3sNAUpYzNJLAdoiC1E5QT1T0Ob9U0OIeHK9d77FOyVu2KAFDqFh7zvPnM0ArORy7KKwyha2y2b1oZkDhmnv0VPXFfG88wA66p7FbW4reCx+VY8Am4vU0rbdTyAupUh8NRAaGpdmWdN/rct/XWIhq83Re48EuqrqYddwJx0QLB1YR6Isd2ujdq2RHFNZ285yBO5D5sLFmUIYw3JweTlKNSKQD6KGwuN9E8cE3Th8o5aGPBBIDS3utTqZSX2zXvYYNzEo0U50/Kb0bQKpMvnfIom4zL2dV3VWz4WYheP7sUCorbFnvvdJuAc2XGTAQi+MSTtaHu4tn1jYwaGrHb7PF2WkI1cFPIdYjHod16luNd3TRW2iPgmqwPcdUUYJl6RaYyjyVXmXikImMgrJfJGfnv+eGQ2tOE34r3PaomtM9v+Hqo13RvwNhgbrViqF1sRukxC/QUJ++P1QmOY9b40jSBZ6iugwqzi8Kyzdm9TRQy9xBp5WZFWKTlpctVkgnernPDOzG/lmSXD1KoBIMX+pixhqAu7/krgkZnzmFL7j6YXQ8XjEbSfKJVgQ2Qi4zIntTl8NfQr19MbYWY59A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: nifi-admin-credentials
    type: Opaque
