---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: nifi-admin-credentials
spec:
  encryptedData:
    admin: AgCRdwq7KiIjwe7CiVWJjRB2LlFJydv/nQC1cIpFVhrvipC0XBRe4vNLzBLHG14eyPs4N3E31MckB4pN+2JadZ3btSLN9ikRNwhaIaWyKfF1MQm4uG/DKPMRR2/BaXy5k6RIDHc7q8jePYG9Q2enAfiWbaGhPlx6OFU3Cy14FP2QWaIGvGsEZ1r/AyPV34UEKNwBX1GJk0APKTgVUIi4KR9kolTRdp2NoY8LjqnYEsP2T6BiQXUNhe0XYXG+0EcqBNN1lX3baS9c05eUkyEDBaaAJKTErxhEPbeNyPXqWj6BKlSwIZbE2Fu94yYaOTyo/FyLBv4o+Mr0kp4cd/O83sgOqxcVtSedr34p/zgogSxj/A/UMYt/sUddIMg+N6O4ELSx5y1qU4MRwfIBbGvmnBVUS/o+KMagEsnS0scNdErWFaTPx4R5Bg0Gc4phseak8gN+74KNsYgB6kx68p6gNxe3dUPzfDl9nbhGC6pJeP9eDphCXAnYuUIdCuwUCtpTtZEN03V5+Sbr8UWiLjLrJEIhANBukAnOXno+S11W6a6b1TAC68BDds4caBr6qBDyk4CgtnYFnklUe4Phl3Pg4zLc1o8fZfl/R3koe6HB98CwxJRSAkO3CVPWshHB6OnRHrH+PPLtRuBeCMt0eaFi7yTiKJomt6RTX86X+jNigd+NGf2nmlmhsZYdDNdTjFRK5KyfR+XV2w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: nifi-admin-credentials
    type: Opaque
