---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: simple-superset
  namespace: platform
spec:
  clusterOperation:
    stopped: false
  image:
    productVersion: 6.0.0
  clusterConfig:
    credentialsSecret: simple-superset-credentials
    vectorAggregatorConfigMapName: vector-aggregator-discovery
    authentication:
      - authenticationClass: superset-keycloak
        oidc:
          clientCredentialsSecret: superset-keycloak-client
        userRegistrationRole: Gamma
        syncRolesAt: Login
  nodes:
    roleConfig:
      listenerClass: external-unstable
    config:
      logging:
        enableVectorAgent: true
    roleGroups:
      default:
        config:
          rowLimit: 10000
          webserverTimeout: 300
        configOverrides:
          superset_config.py:
            AUTH_ROLES_MAPPING: '{"admin": ["Admin"], "viewer": ["Gamma"]}'
            AUTH_ROLES_SYNC_AT_LOGIN: "True"