---
apiVersion: v1
kind: Secret
metadata:
  name: hive-iceberg-postgresql-credentials
type: Opaque
stringData:
  database: hiveiceberg
  password: hiveiceberg
  postgres-password: w70lpAuF73
  username: hiveiceberg
