---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbt-target
  namespace: platform
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
