---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: airflow-minio-connection
spec:
  encryptedData:
    airflow-minio-connection: AgCzPnze1otzq9xUchZsTZo4AivyARekZGxAS/ljAqUcVvZahhoi0Ssr/86OQd8M1KL+aP9BKMWxZyoiAJOWm1weL5/6kblcnrhuhrbZIjBcF//2kwPKAddNDt0Vuh8axjnEpxk6hgUA1IXirnB4MNBsMD7GzQgiLrc+KFB9r8lb+T1rtC3j6DbitkvKE/33L82YfJEMj/dHvPSlIVHa4MWPji73RVO+RLQ9AF/GDoweYmJDMOS9sC+LFxVseEFSRZtYvK60+BKWE0nHRmaFC8Sxa1ENzCpUdp7ajpXAhhwMMGSjPmKzUB/sTGEYgs6yemeVcCYtDOpVcUiZcZvVm5tdE2pC5F+kv8DstrJRtlG5BFzkeRLWhdAAGwMgUmpgHzYLO4QEuF4xvnT0HpLOutj8LWv4YXEic+Yo0ZbsaP0pBd2gEIYf0/7uPkwH8P7S477lnKz94ZBVlfNAsc80U17pscyTbfzE7yrvvWmqOO9leMnGW45jMaoavK3HrA6GtbJJt1K94eAwVLInZM5J5Of8l9E7XiDTfVKT+cOVaIPgQGGoYeUFWo34bI13SniN7/mkQa8OoBgsTYDHYA/275YKwePhF6AVzNZAiBe63VixSumuhPbDGaELiG58mgS7FKMCBKseEOrNhaYesYla+IMGkRkJpiAuVvPTdNlLhpQNCVOJpI3KsPH4opVTWLMT8AgL/+Vhh19lIvZleQG/5XCEJNMzxP7uUU5to2TUX9ilQs0d0WqGTh0d1yeTMjxwlTNcNrm4hNg+aDtXtHJRo+n3VdJeeoVGZijyAt7d3GRjHzflMdTz+LuW
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: airflow-minio-connection
    type: Opaque
