---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: airflow-minio-connection
spec:
  encryptedData:
    airflow-minio-connection: AgCjmsg4pVB2kKqgWXBA6zCq6l1+hFI1inmGFJrtBspRN4/IdM1FwagVmvDTNhureHqf4xBC3obsqvmEW4NBJtWAAaVeYH7PIydjJrk8bV/3kMf7mDeo7ePdfZdLkKoJPANRaL+OgPqjQpKji+lN9yye5NEHRjKL2fPsVo5Qoh/JGxD7bZu21SKLyqwEBCncK2mOoAedjEaElftG40I9Nim9Wt90rMZdyY2IYj1d1gXFl0dCZKE21ZdBpFC5++TYX6X1OOhSLWYQS54i47FRFWtsLV2H5bodAKS9DZDgVxT3cypO9SbeMUt1I1ZvozS8J70j9NDK90x9+B7pFdmoFZ+1jaYgVTDtWM4uj+ANdmfeqAZfBSDsDRFuVt0iwjFKkejLdwuvp1HXlXRZiGygVhDYVjjhtD5Bj67qMZX9wAbiXCkpIGDtNJJLX2fC1c4av2bT+VufZHn6bdLQGfUYCswZv5gU0HMWW/xlh8UFOfrN4uRToNLnJHclIVZwP5dlsJGp/owlXm+TZfFgS5EAjuVAkerCX6GnSBNOBpMyBh3kwI9d3og04KpA6NUfuWdHUlJRkKWIetNACk84Z1nZzTqy/wSbWiwvFrxM2ODo2zEXZfaVBmp5nbXhq0fWoEORvG9ku2MhcJXvlN0ua9HfRLNYm/FlMv5eCES8q1x+QzkuNuyT2qSuPoLQNdF4o8d1KsZykEUsxSiopJKmlOSJVTaqsnk/XiZCpfHnC2+jthjshYiX7q+tPG5t0jSfIvED3V4Z1k4H+asHmLNccTZm/NhTE4IKi3969pMlCxO1x6M6DGWxYfmPGiEx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: airflow-minio-connection
    type: Opaque
