---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: airflow-minio-connection
spec:
  encryptedData:
    airflow-minio-connection: AgCEb+4iRjYgzN16EQ7V7SiX3pb9xdJx/JEevS12KTFhUNULeGzcTmqXnR1s0H4sjIpkyl/m6mBhQakpYJVNdcGMGdWs/ygWx17dDKPLPL1ASfxfzZsLKpGBcAA1Fp6RD3wywwlCTUZz6og1tis7phJ7Fx4N2/5cL0RA5Vqcxih/EN4yWEwDgZTNYP72RcNpDWq6Q8zqawNqemKEMK03EWdusNzJ4dgKNK4+STqs/bD57tuCdHal0srGSLfGUUaEevM0Qmv60iND5Uo0N3cj1gI0CnPKD4+qWfbCZmCJ2VdH/JHqEeM5O+pKH8R339R6zZaXyBtBjR4b4/ofwpqXlMfc9eKTtJN5r9OLrg0YNoU+pkD6KzgsgrcyDJRlI9uB8MDCv2ZxTN13Bcz/Z6JcTS3m4XWE3FPYfwfE7Tv3FK68y9LY96r6HrCQPdS43U4DaCjpAkQhPin/5KdYotDQRpXIcOvSAwwo/Bvxzu5n3Uk8euma1RcYaLCzt2aECqs289l+trVqQdzBpRrR/opZhN8f6THRwi/WbL6iSPeZoB/O89QgrJ9qTq/PeGXAB99eSoEZMUKzUkkNvGFz+pYxGq2sgmc/RcA4W1lv7h27QLMfruBXcCWwC5M/AoqonrYCyfCqVuADp1f1KZipyw/OwXnLzy9dWOzz7bV9cId1B4Ms5VpOHK8XyHmUj2GVy+4dTCB09Sklz3bYabMlUEW/V9i+XMj2RDI0e6PD7KVB5DmQn3mC6OjoqIrraU7B5bL1dcxrAMBwKt2Psqu1WgmD6gSpXVaxQdnTN7aRVOCWodcsV9eSgknw8shy
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: airflow-minio-connection
    type: Opaque
