---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: user-info-fetcher-client-credentials
  namespace: platform
spec:
  encryptedData:
    clientId: AgDDv3i/jFyonx16tfah/iGnASvYXcke2YSaIddvm0rD4l2tt/oEFWpzzyOLCNfACyjWN+DoMVnrcAXubD7WHFIzdH/fVbnGpUNyQ9PtyogSrIimpkYQKoJ9qSWX/VL5PNZXydRdU0m+sG0pb8EHiveaLHJxcG1zoc2CkxeIzNu54DIUAq1m+zbQFqGLkH/OlUMdiaD6/v9lL0BwQdRbNNLU4yW8A8ik8LRGtNHNBGkzIoH9Kwh/VMcffv52oR8yJ8za1Ivs02C0peQGxsABxjnd2+tK8+Wh7aAlnJld5S2UEZTbJBYbpeJn8G3lM1Ks0OUEOp7mWbcP49aMDG44Du2AYCVBOnlawl/xLUYQLGneIrG/60D7W2uQ3VojxyJpwi8ZP705Nlo7Z40AzriBxQZCwLNbSCIJ9iwpoRRIbY2lOxT8RdiC1OxpfhPdAwwh6TAw+fPEN6aHDvCcf9J6U18lBbgs+kiHNJKwiHSi18226h/UcCOpTCnwcRdc8hA7GvX9CCvVpyZvzjC+Q9Agpt/qSAB+fopIz6mkLqKKHsvL0Qpbi2MBekHYq870DH5xgEofFe2wRSl/rZqu66lYoDPZnvgtvHO75W8R//JwJuMezTV8P/i8mJHekkXLv52G2sN+6do9AkfWs0b7FwhA/7liQ8/5l+u3CwfqgherJsJn3VM2nfCnqdEEneguzDDwKXuGYG36uP+JKaAGOGkoZq4ZBw==
    clientSecret: AgAcSo8QwxPQbjyPU6huW99QT9TXYeYBS/xxctIaWhLtIBHGxUwqCCeGCFWuwm6CMhyQ2DZFSyW6pGA+vRTUyIxQShy5pYLZTtlthk6A3ucq11ZRbeMfvXIV/XwH69dXnFNFE+xhRFJ/Fk7E/b0wrFUfFXf28jTY2uQZ8pF0MR5i6pyd9kJUnFjW6T9j1W+IccM9cmKwvhfMJNp/G+D3RxRUkG16//MLaMbOzYvX8T+SO/LeYZJ13Sm8k/0+AWf1CTdJu6BxADS3Kg3OzpwDW5s/s/Nn7vg/S9NAgHAjhTv9vz2kDYOx5Z4gfGiqJP4w131DjrybBP6qTc1NOCahta/eQizzFIMAbx5CK1s9KDrXRLUYuBiMqTbhca02htA3nQTiOyPhLm5X5YpM4l82KF+RITCUSekvyqOsixGJzA+lORlSvMhhymQekvybLtr2O1iB2U0Jz01ll2dHA9FQG2ZvbrPVTM0KtOGnd71y9hcRmQUuHXn8aNMBdOW1HRfQVx0sqAV4LIQT5vhUdywA6Wfa51CWk4cQ3qVOc3UcZjpyT+n0tQQF5yRfFBRZUG2BBtK/dLNB6g8/xlk659IJPzTTGnEm4S8hHpdklIFk4Xlqm/H07D2VHVV1TM5jABCY0megLVIpaAeTdAumauVleWYeGYqq6RZ51B6h9ep2WcgOuyl2h7HlDGgqA+PKq5xL8aRJULCgF+CoQ2DNdzfNr8WFxvwRH11pCqo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: user-info-fetcher-client-credentials
      namespace: platform
    type: Opaque
