---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: keycloak-demo-passwords
  namespace: platform
spec:
  encryptedData:
    demo_admin_password: AgB4NxOt05sAGJmNiNVkAHz9likg2MlwXGYeNY/OFdoUrK1WbmivsuLXIBWnzn1eu04+ltS4Slc4W5ytKGwXk3yw2gHCL767IHvgUnDQ/MvIICCUC59oJwdSY92u2K0tXv1G3Q/T4TIIYXaNZV1uLF+lkNrAp/7ZXeVai2anUVe0ji1kyA89uEfTGges+kAGxpyqKTjyQRycDFqc5hL963QMAjaOqVQWx9/p8Ryz8ID0MlA2BTQwIdt06tKrkeR9BE49P3A4T0zIJ1EL2h2+fqYJhIT0dFHvoRuQV3Sn77BpVMx0husJTh/ZZUzomjayajmXbG2SCWrDouXkgNPfnxgGmSLPThBjoDFzp7Id1GWXW3ifSR537nKAUaGPKoCL9aRIq0o4tSYI7VdnfUrvFJDhjzKVnmMl1EhUEg/keiZqKTPJlc6IzbJrSchQZxmVxhivPDHm3C19HLFajbvZ2ErgSR9EkuynLFbS12k3AxLjndf3uVQE4Xfam+h7GnCJOISVTdZOWMn3r/+4KvsHlSf7LuJd3rskPLrIVtjWGrxMcb1gxkdHDAlIfaSl91gQkniJiYj3N715aPn+l1AuEGsIOojjLTmqduVmfSQcwTNV6YcVeaDiJxVBJu8ybw7FGHcEKsfNwgU8xxf1Bch3P3aVB8snSXMEx+ZfRib6sGzx7Kt+UFn/IHJx2qkJ938ccjbvFYTHqPKhDzyF4vKoAgzg5kp/tzSotyxSXc3VHjDWTg==
    demo_user_password: AgC4cHbOHxxTfU3OMOeghmkaAbJb6m/hz63p9DgfgC7BWF23VtSFZodlm9vwCOfFxTBSRJbfB3n+Se6Sy54qNXNLpoMR8eXF17EmdwIFAA5C+Rtrq6QABNsqlqzwAg6+r1URDK8z8a2I+TPNOmSw9P5kIqU5DyFFxP27GqTtWGzAzm7Z3UI+KziNVkdDId4aj51xhtL+QWausv8FPv0HWG8EfA7Jy/bksDc/Y5K7mQ1vNVl1QJLuT29eUTiHv4yyjCq5G2ZlTwPSWeNahD8VT7aQCZdxqolG8AuICsNYmrxmqildFgeaxEelqcX6VxjBDOwMnNFJxsPnEaGfuw3kG8JxK9uLWAVsAtNY6UMEmb4eJsxSnVvhoMDUColyqglEmAzeH+VgpPlnAMEQu7eDodqWYpKqoNsiflRjvrb+jvv8AHI5ByMxJgbFTul57de12/ulYMZ1OtajqTX1CQ3pC7WB+v6IGYsLgoG28ZT865tVbxuYXiwlNlST8pr+mn/HOz2O6F7O6YWURsaKWjDa+luNL0mejL01pYLwmkRGC+Wz+W99LYWHWkNw6lydSgC4Jvfcfwj88+FI0LcXtexCHdLm2U/XpTf6MDnwXEI0UqBhq3hrRmd5TfZdfzTKqZ66K8knfbIZeGWpABH0TPTUbr9pJvbWgkg96RXoBKuw87gV7Cr5+PtCfbzkqhaGmhvf4itQgv6naZUFxcgbYWrymxKWx62f6GPlOqmrx2P32BQNvg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: keycloak-demo-passwords
      namespace: platform
    type: Opaque
