---
releaseName: argocd
name: argo-cd
namespace: deployment
repo:
  name: argo-cd
  url: https://argoproj.github.io/argo-helm
version: 9.4.10 # v3.3.3
options:
  configs:
    secret:
      argocdServerAdminPassword: "{{ argocdAdminPassword }}"
      # We have to set the time otherwise error message:
      # invalid session: Account password has changed since token issued
      argocdServerAdminPasswordMtime: "2025-01-01T00:00:00Z"
  dex:
    enabled: false
  notifications:
    enabled: false