---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-apps
  namespace: deployment
spec:
  project: dbt-openmetadata-demo
  source:
    repoURL: http://forgejo-http.deployment.svc.cluster.local:3000/stackable/openmetadata-dbt-demo.git
    targetRevision: main
    path: platform/applications/
  destination:
    server: https://kubernetes.default.svc
    namespace: deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
