---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
spec:
  project: dbt-openmetadata-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: "code.forgejo.org/forgejo-helm/"
      # helm inspect chart oci://code.forgejo.org/forgejo-helm/
      targetRevision: 15.0.3
      chart: forgejo
      helm:
        releaseName: forgejo
        valuesObject:
          gitea:
            admin:
              existingSecret: forgejo-admin-secret
    - repoURL: "https://github.com/stackabletech/openmetadata-dbt-demo.git"
      targetRevision: "main"
      path: "infrastructure/forgejo-manifests"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
