---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-demo-passwords
  namespace: platform
type: Opaque
stringData:
  demo_admin_password: i75O0l+mxR395np8xAQ3CswLhx/BV4lN
  demo_user_password: a7ju8wNiaG2mnj/VHBFNslsBY8ia8/8F
