---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-logs-credentials
  namespace: platform
spec:
  encryptedData:
    OPENSEARCH_PASSWORD: AgAQd2r0Qk8lv66t64eVJBqarbaj0zSfL8s77Ls1KSfF8GJjFVbKGJKVFaZRMSvaFhbzXrGx7srUt9dAGw9qgiKn5x7zFCzzqgHLYjF33PXj3fNtclfGSO0hp3uiNyyUzRVs39eLn0KSAfvxU1OYDs9vK3vO4GettQsyTj4dFsym5AmvOSc/DUjU+OnS2WhNPS/oO3cg9iChRClhmhoUUvGddsQ3uhi8lGN2so38vamTXgNk4eXCH0E2XmM/6R8WVUiW4bkCYtqncVA7BoNoSLv2YZsVuOPdW2IpEr1IDyWU0eKLtn6IBmYW6fEZyiBGJRSYuCEDCYCxwXfL6iVGn7TMe0twJkibGkWxuGneYOc6/yHf8Y3PIzn8jBzW0zVbqsiwbsiH4rApUrTVASlj0ZitLcBR0r79sevxYMMLVXEpiH/kw8ZsYgUMzCAD/Kimin/EpvYJGkPTOkn2vn7LjONkewmFSKQd6+wexiMElgDUN5/BLve7UUDu4zoP0v+vRoCdXPMx6x3kKmUmMMaeiPfS8H+I8RvO35kpp19B7Tc3VB+KRJwVaErZ8EnHySslwEPzWWLNhvgPInYFvUXGr1tN77e2h7gAJzZC6r/baw6I3wMGp9bHyZxdEiQHO4Nx32vcmgGNdaGOWxY3H7FP2CH7iTQQIxWJJksSt6o5ZitjzUqHsid1UduNNzdVQ7Dd6M1ZsUDkHvVTixS0pOqMnARKSa2wX6p75k6movwn86ZOHA==
    OPENSEARCH_USER: AgBzE9Q/zk6dWZ+bj8i/2oXG522ch3VXivi4SWBEP24sfWAh24r44pDlajszedG8qvzW0LKGlAvY/2XXNgUivhb6e9T+vcyDXuReyEbfZ+LVe9eZO7E45c3QtMiU1oyCe3n3WvUK3E7tbNMJASmbhUTGsZhoZX46IbdUFKLSDBdJS/wXMpNggTcXR753KbKs95/ra2TCUk74CzN+ZbSR8+p3EsrG78GgOsG9x21p0B7Znr2DFHVmGE+2jzSgcA7pigGtnmstgjbQWH62BujyNdApUsF5gkaAipIJ4WWEX1i0IN9V45y9xoElY5RngN4vz5yrkyVvEgoXo6wq+6Ln8V1lCIPHg8RTR932F8VpwCN8isM11eEsctTc6XGAiqrjkFy0gIfwmywRWukhAqBnO6YumQd5TqWQCE6xP5qarJ/voErX2Z8Oijn41hGlROsw7s5nSdSt9/kntv/7pKpC0znWaQljxTFxe7s0xP4Jmuq2ck5AcIRi4RPJRZuYX/dv2aqYQnVjth+Yr0pO2lonzt5q3vOOO31zq0X/CD4sa+RFJpCQLI9VAXjRsOfb2uyTd5bDkESYNXMlwh5JxBx9aIKpc2zSwaBdN+8HcSK9oSSJSmVBk9TUv2Eh29okdqGjxTEnMN6Q5hGKvL4RHFtK1VLiP09oS4MhrynL0pCYYLDq+0lwyEcDMn5bHpbalCoHt3pvl0Kl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-logs-credentials
      namespace: platform
