---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-logs-credentials
  namespace: platform
spec:
  encryptedData:
    OPENSEARCH_PASSWORD: AgBKNQqOXcblUVA5m4aPMTINcbLNVLzkH6+S5A/sIdaxayR2b1ebw76VOU3mtv6oQjYf7GjmAOax09bdGI8v1yNdY/dmsluyzERquXE8jn9z7SjlFIlaoJd+CYM/Vz/zXUWAS+MphuQtKYWL5zwc8KSNdYnk3lE3AXHd3K96Z4BhRI34E3yAUNJ6HApnn2P0AYZUyBk0FyuMz7yMY5t+hnMq+iohu7GWVlUgnSFtJgR3khx4RaD5WYUOoRzXqpLOIuXFmvhLS19oym8jf9DZE2VaMrmTPhG7n9aD2QjwpxePqh737FAjkwnzvgQsIRiBxDSJRG/sKxBHRP3FMbCjUhcipIJIl84KYMG0jZx4Omyc3cXjPijFRUt3a8/DsScM5XGfXWk1Wy32d4rDaTvBYVttdTTPR/FREqy8K7oAVr8L6RLrohGYxRUJRRs5r/KUFpd3YnZZYVl6MCXgtfFYoNrLZP1qC41D7rKmrZVdrTg1gnhttPAgrnGYx+eckgbBfU6p0vLlL8LwjOze5IHe3HjQVziSJjaWnUib6ulsITKUGP4B5UXkINbbjwUb0URkSSCInBZPyy3/4yPEcmX5HQeMzQJOSR1FrL9OqPuNu5zL45iFFLY0LcWk12LbSapceBxEhS50Np3afoXh54c/nDriEK7Rb1nmP641lV9x65iyQoeowqI8ZPAsQnuicUeZR6PlXwUma7X/dtuqvT2xQpD4dfZDM9JdiUhWg4SvemtyBQ==
    OPENSEARCH_USER: AgCmjiwuEXkZML0e9fhT+Jm3p3LJ3sY2NHG9ApRsMF72ZRexSOj8FWhLx5KQVeHhe2m5Tx+H+Q4/MoK3Ts4jSaACU1ZMth8IrzoT3LR/+cIFTDH8tTl2vCpIxsja8irtEchZnNWCDc3ktfCpSOK6cP5QugcRtxevGTe3HZVyRX8iaShGYW3IwmH12H/iM5MkoTw/VoXj4zgCmwwE+sYGxrpF/n9RasFnaAn+iRvjbAqU5tD+ujefjfWjJ/HExggjNCKnny5dwrBV/UT5VDwlF0gnRiDScrGVr2MjluU576/tW+/F+7/cZ6NCqK9lapO7Xfqk0amO552mUMz08t8SAueR7krbAuy3FgP1M6YPPE5pBFmqOEwNl97tCkIqh1Fz/5VtrqSV5PcORqeJ1RqLsVYf1I5O4Ti0d2mXQQZCnLGBSxsqqhEgjDUrBlY1IaZCvG9S+mNiYy6UcB3cmJ+uVdYuAL4ts86Yq1si6BXFA7l5YRUPjQhUxeqzpFafoTWdzlFAp2W92wElVOQ669eVYFVItwvkAD7RM292klE6tBeKtY5Vp7TXvRw3xTfj1QyTwlqupgnXmvN0h9gmFsqrgXtESJX2ZMKzM59mE0NrnRgHOGGaTDkztJpPWR2UPT8RpIV7HVCcaggkdOIMZaFA0zLKIo2jldohei3L2Hdou9abhuCfmonkRFcXCFc5hk1wxuPzjqPr
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-logs-credentials
      namespace: platform
