---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-openmetadata-credentials
  namespace: platform
spec:
  encryptedData:
    password: AgAqZb8GYiN/mF7X4ntCZXrCWIO+A1aWaOVc8x71s1/+Gj2+8mJOzTWjv0b9Q3jXIDqwDKk2xqmcmVDOg5ZBFXI+lk1sgnwStjAhbvqj6D1dgyZ9FZcxy6lwFPsbxCm14FzuPPKKVmuQw0VjslqmcPWDGOhi9yA8Swzf5/g5ohr5OOM2AiNBug9BGC4r4bMOIfIo5OYS9yJlNQVptqMv68mvVjf8sIntUMi6iTG44QE6CvrmjN3QpE92QneVHFep+DM5XXL3UbgHEdZwo03OSAmWdmGd95WExqzzBJzSPnrBxgWuC2t6iOA7JcrXVoiDeBMWQdLBAot5KOLAE2XlTdbOPyRvhg/QUsXUNQIYLNqYCHzERN9DFTsYnNdzZkyfadV0uIxSYD00lgiKzkn7TfOhnujuz8Zo/oUEN6eO3kJQgsuAPxpc1k6ubAaqknX0G5Nibej37AwPzmVkIetLbSIm8P3X2o3ZNM0Tj57BC0Fx6AQA50dJgWCA2vNvRYeXNd0BWBgCPT7lxbYOluM85WQCTXYw0CR+U4yf3MuksU1smINLPUUa+t8cY3pZNrN19gnaCso9zhJ1wiwbCtrfuReTgaeCHt6R22gAeTVBxP4N7SzvhQaftPt7itHWPcgwGETM4Hfpzur5wfOuA3d5tzuRpVKCeydnw1qV7VQhudA4uBm5dtVHj2c8meaatG9xIr4c6e8jEkOo/juwe2e4NupilhxHlAzyzmkyR1uXnApOkQ==
    username: AgAxHNHVOUyGFUr+fK9D0syIZXTshgJWfToWzEObjJMzX2MpzQibgIBvto/MVeUfVAnZSRR2LbmbIhy3txcdDw2GuLAytKcqwZINOChPSimplYi+6EkUCcoykMZqmVBNhVhANwPw6EwRHE4ccaCQaTWbUBhUxEWHSN689uyzOfQ7a+nNCCh/5X972O3JauDrflK6ucfU84LOYD4ZQTKvl7nOepQWIyz/0TICt0TO+ClSPpn2VOz3BWIrLjAjGuBNp3BAHQTT9dSCkroS19dVCb2jfp+QQP3KDgDUPikdi++Dk5OmQWVHcbD/xYhlhyLm1ZgpJaBEMx+pTGCSl9354SJ0rTO2kErJYkPtKeDy0eQBWxSgXJ5s+FWrax7z8baUM1wDHAhd7Z6D7fnvYIlqxkyzcor5FT4VnNe/xWQ8pSavBg5nkqSKU8Geh74g7Eg/6hEnY/NC/e1qlxFPPDweSjoKVL/0XMO9Z+5+Ouh+5flQOjQ2s5C98conR5d2KgXc2XProoB7AVt2KqrtkK75bz2rzFI3I56oWM5mQhJvNJ9tInsS9DtmDMgnDHKQwr0yYsC4hBz5ajEae4i4mw/s0RNinpR71DdTBu1RMQNSv2gj4WF0koFz9jqBKF+wlgv0rPKY2IEF2Rm/LJfkcczJ6VPs8BxAOSaT06YTJNnaBSYsurqqc/PGbdzHh5VQ9l2D+HOompujuZgvlbI3Wo8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-openmetadata-credentials
      namespace: platform
