---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-logs-credentials
  namespace: platform
spec:
  encryptedData:
    OPENSEARCH_PASSWORD: AgA8LhulkOGgMr+q1hwbWrnk1BPmQZaIvxE+1e1z3MzCsAiGRXMmYMtYpD17D+ZNoX7Z7vLUdJHFZPSqf9MiiCc+Wk6MEEKMnfGa+Pyw935P+wHZAvfr6xeY1DPALwWbTGt3wGQLNgrlpsWEdZ/oiJD8XXhlaOdRv37hMkrI1k+Y7sUEeL//dFbCesI9vKvzIIlzmlg8TgxslffZZ01bvFb5oUgQe/q1CvkKmhSBzgJ45DSjgAQMW52S5TwSvnem3AQdPJeLT9dgWRd1kAx0lneEMsei23ohLQTb4z4BK7kNjwMMm6YmQlnrSQI6aIF1wzQz6G3UMBLuAZ77GDm9nL4xqx1HoCtKlZCjxu/ylL9sTm5BJS0w9ZswAXub1BVTpvgz7AphxUOhQNYbbMrJ5MVYbti1te5LKaQIjvxLURsLjxPIwTUCkC+6N4T/RHvsa3EhSM8VlLP9OXjrpBjyViMlV8MSXxTrnguRdWPAjgeJLBptYH7duWnU28eItL3AN57yCp9FLxo1aORBBRq2pnxIhVVRJqJgZ0bKmqgWR2wuDh5ak62aApxsi5/QcvRAsohdwmYZDwkpH3ubcYBwkvvZJaRUazJKg7sIUUUuFfIan2X5n1R7NvQjnyxk3dJ18TZqnE0cXLoNacpMeuzkjwuIkgpAJPMCCoORTcxXxauKU7z746r5T1v2mBfUATbizW1+LTf+LdXOk7n2qvBw8tt6bLqOpevTXUR2cVyRLaymEQ==
    OPENSEARCH_USER: AgChXGwGKQTsQN1HRA42az49/1r6h1jk2aK6SmSFFgWQfELbtTLk+P3wGR+l4P8yB5wnvl//wm2G3FvnnTXE+aSeK4egVR556WD8iwmLTyDkw7xEswY9xhgkoNTTYF0+bPwwgz4HJ3/zi8t1nRVcWnbfFAqlP8ZtSi0hvsviXPnLXpynOGWfMXOGVk5A2L7U9MiMnXI2I9OkSakUqSVadxqy0K2jNZ6c5LWHjD5zjBfjR0+aKVOo5B8fH1OLK8Loa52BqKnDKm0aJVDgl7S1bl5QFrksABuml5JlqoKrhLbMLVWGG3DuaqKIdKhav/MSw01eJ9goCch7B4qk0+57hd0/6zXvMpN9tqencnmBAsLh+iFWzGILQu5eoP3laTgM/dtmBse3X0WNB05kKBHEAnvumo7xBwuAC8kEe9FiOc8LaFY6t8w8bjsk2NNe4SrtI800c+PmLwh32fwwwsbw0vsVqUbyGHMnuqJ3X09DMK/krTJ0EWu599M4/0zRAh58bboVEN6zQVR3owc9vKob0zLJfKD1QWrElRpuv9OV7N3+pEchQAGMGB77YViwSKYdLa9j0yq5lVyHeN7k4tmhkXOJ5j+V7xpEeQrZf1wo7hvtDzAtG+j9Prf08CUF2f1KGFNct3N0ScYZESY3T4CIsa7wWBj+7VOggu0VbTSZ7YarU8FKFfM6Bql/E10oJOJi861wiLXA
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-logs-credentials
      namespace: platform
