---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-kibanaserver-credentials
  namespace: platform
spec:
  encryptedData:
    password: AgBfvxG0H3q0S+gfc8xN4bS2WyBuyIE33da6K69O4Jnb2KhP6e9aA0G1Hgs63/1UBN7DDEEmLUtjsYHtMrOeJjd87z/i7F/GlnJrqNnIarXCZhlAR2hCPNMukLO+T8s5mZ9hFhlMDm6+DtaVDn3X81M5CFZCXkV0K6hrOOC0wRkSlLa3ki1CfL8Sx1c8k/EwFXq4apVI1gnmtI0eMJKP1iiujDbE35fGYWsgdXr2OviXP2ki5ZSBbXl6zrI7UAsUGzPH79B2LC2imGHyKCtlP+JmmM7LHyM4nGSXP1TlapNTSiwmIoV+uoEZgSJc4Wk0R6ZAlRpO3+4HnWqlEaWicdSclRUILDy4eMJ2ABUigrTos/4JfbqwpO69CRLRKRlUUkMx2N7oufmkniqWcqvkXkWmWz7JGEW2rKjJ3MHwrbIJmhiEnKulLScAtukTtYKU88d9Rr9W0VXAY0Yz3ODEEa7DBxzMBJOCSrnKmX7hpRHsmCtrOe22dBQ6KsaQBzHEgAOe1t5Ij0RASmzQpr6yS0EQdZT5Z4xUBWtEj4DuwrjXCIYLn/inPo+JhUwKQQ+sRxDngXFiOn1R0KA8Q/Uv23mimeIqjY4ez83IvQ7KM0TybQRhjk4Tw43hty2NR1Abq8CDFuRrbFoiGFf5fOJ8Oz2kwJPVhAnnvnrextDpr4h8qBMBbtUSTTRtmCTDvFelKl+RGzJsy5PdD2pLLxVrZbatuYPFDxLn4BCNuACL0AXqzw==
    username: AgCNBOGypYcJXa3+dOqrrT1tZYLDaZD2ukMx7WHOWkcsbOJXTaklwWmYvkfoIgoGRo7GZNSa+tDUOB1gYNSdfTD5ksUD/zsBKFW/q6X/vxbjOIt0GrGNSzMjIIdffcxPkE2ckVqcu2Ki+1IhpCiV1pwTqPbBn92+uMUtCXz67AveMiweQ/Y+BcnDxR2LqnCL18judoYci0Iy6pNOPeIz3K55ezmcV2wfwpuWeetsYc1gJJHurUOBSjFGQJxyoxs+xI9kIH/PYDJtzUg61sAZhEBeCuokQdKDUs/k4HXrrqj7xsOgqXJu1UhurdeJZZI/BhAOhv3Dg8H9fPfMcPzFenpW/Cn+IyUBYL0rBjFbyHSEUC0C2040xq5BTJEEe/4KJiZYBmtpWEugpBW2voabiZ+oPId+dLbdyWc989/23Mq2nOEp1dyAXshRpWHl69pEA/MyEQisedkcFw8eiXBxOUj9nLvjsi6wlopL2GzmYr84HE3WwTIGDX8fkuvsomTT9xLI1UrkP1hMb08W+0gkrqg1qBzmogwh60rbjPrKhSeu9adN1c33FpihFWDSwC9ecDLshCjqIwPmxmP4zCE5DPu434w1tdhW+RtjF+hCS1jWn/ehyEiWJIWDQtUO4Wji9asneQto7jOHbzrm9d6Ydlra41ZV3cXSE5RZXCnAwzz010wp8mHbyxgMh3pTwnq69O+kOBFImd9qv1nE+ao=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-kibanaserver-credentials
      namespace: platform
