---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-kibanaserver-credentials
  namespace: platform
spec:
  encryptedData:
    password: AgAaimvhz58rsEoNzQrfTf0kAs9Pz3MvELebAkbkOfa0X2vMR2LIjTaiQTIDGeAnWRNZzsO/MW8CBaleORH5T3RI9ILQOHkDVjpQQOFgOUFs/v/cQetHRTbv5x+wl5V+L2Ft7pOaDFOpPqI0f+78Taio84fqGQYgR9gIJ91tZwAxQoGG4CTBONWb7YNelPcZG5rSfdkDiZf5ppG9SauUpXWD9txyOqcJqDK9xbMriR5gdk+oAR+WZnomGVUabHuQKzt+r1uuNlHp15dA8JAx/cjn29VNw8pOcgSkMLDtz4JGoEROU67/LcUU84JOqP/ZOrL3iy6oq0b5PHjgRiK8efa4xaYvWEU/NuNEDD/LbC5+38c2gCfCKMLQDo+9XHuwXTiBUEeSn64z56LE3o45XdrWoZgwUryT4ebBXlW9TK/91UO9uUR7Gg8lKj2YFdPciNLzeCVkxl6E3xjjBNSGYM96GEaisiKOcYfpUvpl55h1iGBBFKOqUQjOyDDXtUn4Xn37yJOBKLdF0DR1YF8yGzRgnGjm9JxLZ7Qc0vM/qzAyLlOprqJQzUtG/ad8o2MQr+zGUnXmrMjxpHcc2FvwlPg2KwncR0EUKBcAI+I3uvDpxLlgfov/LOizRb8iOkj1OE3N1mIRi2rlWV+hBycKrPDiyd/a2tNDarf9WGLXQI4SeNlMfkBg5LBzbSwEiTaeBKf+R/cLcd4YwTuBvp2LC2LZZ91bObjx0jRZRsktPu6TpQ==
    username: AgCIaRqBTrexi0SYpHE37P+uToXAy2n3Nrvp64CtXf75GdL78OP0qm92osza4G5pzbamp8eUYIRTC2DycXwsaMBcKakPpU+7soUmKgO69krtaxjBhlWTDb9jJJykUg933NP3xNw+9gsu9hu2/V/o0t7mRDPI+5QmSLwxIqwBbQLOSRCv22h9x3BuxXw/F8hDQ3348YbLaNSSIEzZuii+Y9SEkth50fdXVWdYYIXrt1TKJ6Id6mdfbPK/OktArxC9Vcd319X4we0lMkTgkAvfPKNwkY4ahzF2MOMBuuUWK9FlXsjA5ULB33VsXwI50DVutmsLiO8G1VYOoxTYrfUil9VqR6WGuABsQynXpf5aRRAuJTJ8fmSTyDuZvyp6eiGvRbEeQv5l/u7kAHJpIyPBFqdV5SBEbcZAaDqkAuWWEOfdZg37wtslIV+SVM6vc7fxGtdJI7Q52gzFfMrjmi4GiHCvbOEMn13abh/X1q3zM5bDq4SSt80+yWjcklBhEtolfDpupyY+0VeOBdn3ZmWePBiZErtzDfTIDwlAAPAXbZEMUs5YWPnQS6OM07zs8P1zBQUzctholVMoHLwx3NMOFstuP+2SAWnJeb5pdAGSWI4oS2AJGeZg+op3LVS9MC3Xm8+xqoQbkDJu7dFFCO/C0RwQqb7suav4ypNewdv7qH0q68x2zx3BtAFwgiFY4AMp66PlxnB4CY4xyAD8VeI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-kibanaserver-credentials
      namespace: platform
