---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-kibanaserver-credentials
  namespace: platform
spec:
  encryptedData:
    password: AgB803mohBlg8cfTMzdzEuZWACk1FtNQCsaG1Bakdvcy6GrrjsJucaKs+oSeccyUT2X9xlQEoHzmQDxdnT4HL4r6JYVUdi5f/Ad5rKWh83oLrMkukusflc766dMZax7ZE8PUNUk1BEXI6EhHTGbXPb/LAaNQbUsNRrHSWn5cD4h3rWJDOhEwb4wkFZ9GxNVhArJcZdiqhCJJ5mQ1trmoHba12lb787LY7cNqBi5em8X4qZse00RDdUw6tDHlzRx5rkOwsa30jk7zU81RX9H7AHVVqgqwG1ckCef0bq9bu6OCx5o0ly0QyVTOzbVhD+b3P+xQhSKbtzg8bXfNYZej8zcfUM5HDEO9yCLE/dWSIzJsjS/goUIPxlrqYkjWC2Tuf8kQ10N7rwnRXWEaA9cbEHyeQM6iOXg6TdGxRl47x2yDjBWs/sXOc45I6tYaUzwrKFMj7P2QcdjGxEwC9ueGB9gH56SOkhvpR6oMfl4Ajd5660orHYZ8a6ln5xxUSld73UagODMRMgAiSXIUM3QS75u6+H2NCjVIkUCYPl5G5+yKdIW+mNPtIqt1DlEgNSL3k0F4Ktpqg2JGxdtOd3l1Nu5Q8GbMwuzIJpX1TEBRDisi/JKLsZPYirp2yCg0VI/KJqQ8Z68azyapfS02LlATpaO578QjZG4YxfnoDMB22+PQqKzMandzooGXVClRT3mnAtIPU9AcrTIfv/sFW+ybijhuSAhpbk4qSvaWsQQdTKoxKw==
    username: AgBRFT0uata4k2iGbkgt8WXufqh5nFQEERQLgvg+/TEfbxIEy3YepYMEQmf9O8D9AT1YhQ7eDJH7ZeBwKGrk+n1gh3X7TexBgOfzMdYyY/DH/xJTTfOL4A9tRhodpNHgstf/0f5ZL58AptA9IWnqK3mMRbS1q57IHM2S9hIWwQZpSiuusV9fgOosNcchYQ7fB6mPOsiJ6+jkgPzMB+yGPzZb61wNZGOJX0ZF9qteW4w1lZQ5oLghF45V4zat+KSUKje5qUEkajWSBrI5Ycv8SuTMXKGtgnzl9OTkS+uor/Js9QLII6QHrr/B8CspKqaSWR5Z77OZI5Ra4902s/zt8tR3XTsa072Emx+Zyq1WeumM0GfJZIjJYJGBw29N4V/nfJ8dGJt90ceXzdBMI7ZxpW3IeTLY/3uR8yjWqHncEiWAhJi45wsQjY+P/2mWzbnpSg0wWS2ufcsS5+9rX5BBwoL9P7C3CD2n9CO2DuL9zDBlXfIX3A84CfvhFA5LGaBl+sF4pBuwyql4GmbJj6b+Ry0ebgsuS7GbPQbBjzYv4Y+mAnvLFvOhaJMo9KwfLeHrWvpUMwz1cCJ2/2Z0pwdTzMTwQsZJGwIjbiZjs09nelZZV8+FptvUdAI37+TZxk4yLIcRxylZrpfFftTFvXrbewu1nj1pfQR8dQ3PSODvqiyy5/aDa7MTtERkquyXWSUew1CeH87XbQvPhVDUEoE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-kibanaserver-credentials
      namespace: platform
