---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-openmetadata-credentials
  namespace: platform
spec:
  encryptedData:
    password: AgAxkPVbwUo9nQMt3+53eJ6oiAIbWJFZMyTZCVrb22lTcM8vbpsbvFnrcsSbeT30JxFMVYdJb8QVDjuTVwVz++WHEDzoZRRfkI/9OJdz0xijDhy13SGQ9suNKr1lML1C9Wyv6F2S9TFX87/RosPDz72VOdl0WXYiAbjRGT/OCBUYsPCThrLL+Wi0twKDh7mjV4YxnJz5QrvBylqAAT5iUT1SmWt+aTdmPLSCbZYipqTCW4vpQa80FGzmyJ2RdrmL+xJxxPoJextp31IkZye8QyimQdSH7M1buzhDdXFm0y3LxZ+3zJX5OCQOe7/d4VpF+Awm6XOX+6e/b6ZgmhPLXme63XphaSzFTbW+Gyr/zOaaGGyz9C4VrSl2H6OPkbKx6YLZIFxBNs3fpdEzuOsPY61J01Lf5PLvvdl2Uf21DdygQ/6Oole8x0jTKLuqTllgiVVrksqvNeg5enOCjHuK6FsESjccpylw6TFYDJLeSjLc/6LYkcM+4gaw+p9KU7+n4QFYtfpqMgk0Je2oRw2fY3DSPTOEuj+jneTNARa03hIDUrL/6K7mHYXOfRrwcjP+T4To4r16zf6nBMkw8FT/NXBzSuXIzkgD0NgbPJE2xBLzhg1KfCooqfuSuiYsYrrWONhU3fgZeoKtjUvE90v2GGbbxgRhO9MbX+Mpz3EC/T0p/M4Yiggs3cftPhVCQQoAZcJo655ZfqUaUOT/dxKQO6SF85vL4IRzb5+JULxbjtf70Q==
    username: AgBPhf3ydFZnPR84x8Dp87pV+5xxqm1Cv8atnnjBPBV5iMIuCr85S77uu4YK3O5itb2mXeynd2HXQGGPzpJxn04GW3RscuOGZ/AtJhVOIy9plhz+8pPOfG2tRZC0xkLUwwO6b4OitqSZaYjTkB59IJrpgHy0fJ/4X5HBBXnaS1wD5LofuYG+eIXzKV8DyPa6AurqBoSTtEXT5ZfygEZjA1hCe6Bk3+8N4mHlxTUlNe7vsfQ3yXCX37dSJ+8CEhCOVGijxp4Xw4EocHQwso4WplYQsA6It/mU5ElWvkmJSDzyJub4BGzg3vALrDwRhSlG3H6vKhBa1t88/YT81Pf2CVn1ZJVhxmOtuPPHb63CQ6GstG0tTFREhya7U8jZAw09FRN5RKY1gFqf6X2m+YxFohKwzH39IRayRTcJyDZGLUsniNgHKw6aeQiK7Y/2NCtDOn4In3QWl2MA2CQ47NCa16KGEg6/vvEgl/GMJrOM35Zx+/5LQYIvOyTiwJ/AaDZR1dDvUk74LDW9ERj5m6pX4tjBbZ0qW/15t2WRcVus3nBb+eX6ULXCOrRsGFM8bHBhSBMCA0Wdy6IHDlgvQJX3stPx+Vako61Qn8PdaILTqWTkf13d5Q80353ROgO/EMzsNM32dcBUnvOIpjOXi3T1c0aYFLzbL0UwT1Vsb6WZRQ8bRpIFS09mS7Gwwse8G6ohfhPtgxDIZ2J5NPudR2g=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-openmetadata-credentials
      namespace: platform
