---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-openmetadata-credentials
  namespace: platform
spec:
  encryptedData:
    password: AgAJPqwi8Tu355372ZNkg8BULtactMQZnE4Bnf0tS8bRD2wU6tCBkjDVNi+hIyM8HmR2gUcGw8F9fLnNmUXrE902ZNDCvsZjW74rLxOQX9glZ40cDhnKBLCGxUVl+NK7tFKqHh3umhjbGH9CVOO6FwC0a9DIvmD5q/LdaKo8GAdZ+yNP0F1XoFRGHijv67UwP42gKczeX7Ck01NWpv74YLUpqFnpjdRhHI0Zm2whXOBxkQ9Hq9Dm/Vr7ADJPdGzNQZ/2ihz6qomjQF+YACtWcwvDlQ5+UTzwKbYLfdUiY2gEy4VecrQpassr5jxW8csUuoumc813AGgDIJPXptzuI2JmfB8UoPeYen6/yLet53o64YvlaEmgGpmD7pUysN4NWY/tK7f+qGTql1SRYSWgbd+X65CE0sHjgeZKF1SFhqfSZqtadBvWUC7Ym7ARZjBHEBzTysv59nPayesEcKfhuhsA423zcxJS4wAg18ynW4GYPqtwqCmLAwFsdn+hnmDtBcQ79rurmtOUD/SbMwYiVJEUckPWj7hFZXrL3QOKK4BTzUys7tNyy3V4ykZgmJSYPeF1dEBoexOtUvJBVnc+SAilwPhEG9IyaAMHl+vc795xq9uIzPCTRw4D8OEw1fcI2X9p3c7H6Dp55hf8D8S5qv8TxkvNnMYqwxbr0QRJA7SDFetrJ4wxo1Nnf56hYMC9hXxDhJ7nrbd9Fi/BQwFhO2eSWbeJMebT9WVJ+cuS2eGdgA==
    username: AgASvi6Qf3ndSUBRZL1n/v6vbVpcbJ3veJxdG76ynUfzci2v9LZgNTB07c51INrs9wIakeBA/XSIQ3Lqnbu+81YvfKI5trVtKRP/Vw3zp4wl3IFbJ/ASlOz5mTByDb1escmHFopgm20cDkbxYHiofpT8bAn9DzxNr2bt7VJTJhHhClbZSRcVGwZwUHvK4xXbuhKuNnOCPUJh4NU/UUo0MtElZ/4YHUybpEKjbpcR5kSfc4IYk6fqZiWeHacQf4DDErVWNIbO7WRZV/y3aU0D/ZnljTS0Xz2WMJCf3PworVAySQDMiqL9OTG/4GGG6v/tivo+bL/eYyobYHC04pBh7N3aewuqEyyOvelNGpKxJSrzhTERn7tWvkDg9rAMaBPhrQ607/L4lBKuwOuVhQ1v1U2JY30S7Y0vso/cFaBDjg20WXZiLXbgwv1PjCXLz9SUvVSOWRrHW4K/llm+mLrZnwoxWdaJDDuewkItSEMx6kyG2kt1FhcouH5Ea4FFYpBRZYwETyCv7qHmRNHclm7CkWDjwmyVscE4GR0xnNx+IXwnNLkKZgOxIf5OHFpQPk2z7x0brikSKk0dJOivPBKS6mhYmgy2TwhG7Yxwz1g5Euz00/sJsLLRdwCsCz/k3bI1RvdG112P+6Sniw5AtByj93IMlPf71zsQkSccquwjmRzQ8yNdl6eUMzLdsQqqZ3Sm1/+07jhA+j7J7Purjew=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-openmetadata-credentials
      namespace: platform
