---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../templates/trino-sql-job

namePrefix: trino-init-

configMapGenerator:
  - name: trino-sql-files
    files:
      - sql/001-create-schemas.sql
      - sql/002-create-tables.sql

generatorOptions:
  disableNameSuffixHash: true

# Configure Trino endpoint and/or authentication by uncommenting below.
# patches:
#   - path: trino-config.yaml