---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../templates/opentofu-airflow-job

namePrefix: airflow-init-

configMapGenerator:
  - name: opentofu-airflow-tf
    files:
      - tf/connections.tf

generatorOptions:
  disableNameSuffixHash: true
