---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: oauth2-proxy-cookie-secret
  namespace: deployment
spec:
  encryptedData:
    cookie-secret: AgAXVqX/bi4T022kL3dH5s6aEl4xmxC91Uz5RAMndQuGMfVvZNtrk19e+wzAl/l/+REKMhuEoR+FGheau9ADfJHcCJlLGZZThXA6TZC5BqyxHHsjGXMGfHo0pLkPNgkJVYk/b/z049d5aVq9qIQ4ehqLd6R60xMZlnAs2HxDD5St84q06qgntj42suscH/S4N3SyMdgtIeqUKBv7RDd6PUFxpgIAct9HGKVYZwMFQXCY75eKmryOrK1ZAY83P03dq+S3ZJQuRj4ciCgRGiygCBBS+PdtysIbuK7OfhQwgNto/9FVoCiV/nTVYBHURynSEyQ3octvqQ8HZ3e0YgMEcb4THQhymbUMIjcH9e/atrKr6nd68klon+dir+EZ1GlmwJ55gM6geu2SlB7tX2khoWP0UIMRKIsqEkqVDhehTYQxBU6r0Ssw8JfHoQwRtpj328+s3dpD4/4/lKRJa2Zyt1uaLkhSY1UYyGcJM/jiD+LMH2Qx16gSkZkt2aWDFs26nSIpHfHXvDNWK+OnKVTUsvmaIbPrTaCq+l1v0kN9jMLWPxLjvcm18LcbnLCH8eie61a/nwFkYHQxFCHzDlCbyE1riUpXP9O/QK20/TfvWdkNK2nbV6LkTkgprgE/ffEQ4tEe0U1wbklYgrOTaZ136aqPOuEErEQr9FcwCSohEWAXJIqI0UFKVNVHK4nCxn1euh3ji4I8TZlIaIfC4cSHKZxHAfSjEWaBm1Asy7t9TGgPrQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: oauth2-proxy-cookie-secret
      namespace: deployment
    type: Opaque
