---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: demo-landing-basic-auth
  namespace: deployment
spec:
  encryptedData:
    AUTH_PASSWORD: AgA5lIMsgWz+lFUrsQMutL9AiMs0D1raBfGBWmP1FC9xpirVi3wYg8qrlhAYLDY5abEc1stjEt3KteW+C25bJTR5LH4qInvpHHTfYWJYqFhTCPN0u75e7IxvZza+apsWQI0jd3k9PmkkETv3fhPm0uO7oJifqSzzJ5YA4IBzrTmop7jC89+krHVhbsSLSj6782At2IQPkY/OfAYJfGLUktBNUOI4Fkc+v3360tkRTrs8DsGZx75fdcu4asgEDBc9XsyYFdI3811v7TDwN2YX9XmTr4hiBuOIwiIk4uuOVF3gf2dKgcHXzKeuFhAtFG9NywnCm5FTUE3PqiY1wfk00ZEgQOsEtiWHrTRocP8daPJAzVqaagrhlq7wsxaLW1/B3q2cJ69GE1Kn9F5QmWdV+lWU0hBEVFGlb9A6klb+TtVezoQOqD0N/1CE1wSgOiFTYW5zZuUYCceSzMnccPBmLr3NTExuHqoRtatqLKpJx8f0kl8VPiYB6dPMJSnez6Xio6Zt/VG5G8Jax53MvycvAxV1apRCMduCPNjkA01nVbeikZLT9qagwkzQZjs9juZE+6ongtOxZNlNcqgItiS4rqfep+fQKp5aOU04J22LhXQ6ySwHNscj6DjJsRYrobDYggYvoFMhDQMbagP5Y5SoRJmvaJRcN6lwbNQ8J7wcRI8hO5w3/BvUTvqiDJ0wtVAx7I7OcTD22qsBi2heEx8g0YmzIIi48QFs4skJ7ah11g+R/g==
    AUTH_USER: AgCglzr7xMaXfMn5bAd44l40XLxTNTmOGjTCQvQ5LAG96g69JAVZO1vBc6bASTJEwnq9djJiMB2Y8WfMY0Bm4IYW9yf9tYtehc4CguLTzA2xBnkmXu1Q7nqMbUO3Tx8LwmwDhZ+aAM8UuhfbYUkOOGmSo/OlL+VxtRi7ur+Z3C9gP/uvrsdc2cctYLY02BOXPSzL2HPHbteRvpd8W3K8MYQ9D900ifD9owaqtoXptG8cEtpfL4CDrgmDPyzWLo2B2IrO7OeZitv/gUrErrUGUOgyRRkJVTIfA1SdKetFBxla3SKTTTIZOnLuIxDb5RkdmCBoO5P+1C9g/mMefZwtxE2QZN8agV5P+74VJ70TwsQ6E4p+WByWvnayngT2c/oLwECNChHiWP+r3GtF8yL32oZkKTZj2kTe4LBvjxkVasQiP6TisJ4ZNxXOTSBbEhvKISF3HffMEkT8J0B3s4XqL4JpQmrIQqrnkM5oqrd5xdL3MMkjx+No+ap9fSS21qUDjwCaxlGZ3AzohbyiJNm7CcTPi5Zd1gd0/t4d3w4HRVlhmsVd/O9HAHQf0tFZo83lMVmSY/Q0e/Z5WiCIi50YParnDQd/xFCHr63zpRhduz93NFHBP46Ujn0jYaISXDwconL9x2eyLqGWhqXCxqYb2yaF4rKGQXT58BWfm+uWqYErSM+V8smDvmTmZE8jBkF18VmvZr8QTzBxd0w=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: demo-landing-basic-auth
      namespace: deployment
