---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: oauth2-proxy-cookie-secret
  namespace: deployment
spec:
  encryptedData:
    cookie-secret: AgCrxy9FDalO7ah8+SWdJSVcGSsd9YKTq2ZUCVbZzs74ssXqfG/a0GJdfFNnmQLfR7jWT/+MJAKeuCH5pl/I/L/72WPsmaMcnVA3XaAaQdpuPWi9nYqNtMzkbzJJKo6RMC1CM2RrxyiVKK2jjI/8qhwHzuDFd8xgtxH/trntbLx2FNiAF1Xy8aRo6bVbpprN2Y4Jf5qBR6zT5CSIirGlbH/zzGu/Ms9kcrlMfh/XMkH7J6+tDTmsddMchX/JSzXvE/VlGftauJIXNFIUJlCSEYbE4AFYQ/Pclmxa3JFmfUEUHDp8CwlrtwIk8Fn4tvqsyDQYcqmyzfClI2fKE0SnnpKwq15NIo619BxZ0mEenh0TSg912ClGl/Ox1jVQhRsVhlzQ4MtFjOKuxrR0K1qZ8Q/FTXiAq9fHICLmZ4akkruBjPl+NMyYMXWZPKhYIzfvgD2jbTUigQVJhYXZcFQeyEILYkbCP0qlYIcNHnL/rJ51efEk3qa7g1SU8CNm26khCGN8YIRFxREJrtAtSq3NAdZw7r/LRpDz0CvGVDbDgi8r6PrzoquD4GbCOtGMxpVIT/pz9cPMNTf76kO7JfOz4XEk7eFQeRkJMBETOGlI0+ZqhKlcv4e0LrAwarysPYeSORtiQiF8pOVhyz8y+oAE7jXGedPSfq1+PoOVQTiW1IQiEHwhWX+w08L8NREnWeLnBG4ZEhntfrWXjRsJwRCU+0rAjcPtHSpDbdWlPhhvDRfBrw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: oauth2-proxy-cookie-secret
      namespace: deployment
    type: Opaque
