---
apiVersion: v1
kind: Service
metadata:
  name: demo-landing
  namespace: deployment
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: demo-landing
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30088
      protocol: TCP
